Repository axonivy-market/portal, pull requests merged in 2024-09, with the labels that each got.

#979 feature/IVYPORTAL-17458-Quick-Search-function-keeps-working-although-…
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/CaseDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/CompactProcessDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/TaskDashboardWidget.java
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: enhancement

#1003 IVYPORTAL-17522: fix performance due to hide systemtask
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/TaskService.java
Labels: enhancement

#1015 IVYPORTAL-17541 Custom fields are missing in Excel file in Case Widget
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/CaseDashboardExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
Labels: bug

#1014 IVYPORTAL-17541 Custom fields are missing in Excel file in Case Widget
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/CaseDashboardExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
Labels: bug

#1006 IVYPORTAL-17429 Close expanded widgets with esc button
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: feature

#1019 IVYPORTAL-17429 Close expanded widgets with esc button
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement, feature

#1023 IVYPORTAL-17410: Change the message for no tasks/cases available (#1000)
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/CaseEmptyMessage.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/TaskEmptyMessage.java
Labels: enhancement

#1009 IVYPORTAL-17408 DB query for filter in task/case widget is executed 3…
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseDashboardWidget/CaseDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessDashboardWidget/ProcessDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskDashboardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: bug

#1022 Feature/ivyportal 17304 hide fullscreen mode widget info icons le
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardProcessWidgetTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/ClientStatisticDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/CustomDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/ProcessDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/ProcessViewerDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/StatisticDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardWidgetType.java
  AxonIvyPortal/portal/src/com/axonivy/portal/dto/dashboard/NewsDashboardWidget.java
  AxonIvyPortal/portal/src/com/axonivy/portal/dto/dashboard/NotificationDashboardWidget.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardAddNewWidgets.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CustomDashboardWidget/CustomDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CustomWidgetConfiguration/CustomWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessDashboardWidget/ProcessDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessViewerWidget/ProcessViewerWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessViewerWidgetConfiguration/ProcessViewerWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidgetConfiguration/ProcessWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/StatisticChartWidget/StatisticChartWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/StatisticChartWidgetConfiguration/StatisticChartWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/ClientStatisticWidget/ClientStatisticWidget.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NewsWidget/NewsWidget.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NewsWidgetConfiguration/NewsWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NotificationWidget/NotificationWidget.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NotificationWidgetConfiguration/NotificationWidgetConfiguration.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/SidebarWidgetConfiguration.xhtml
  Documentation/portal-guide/source/portal-developer-guide/dashboard/dashboard-newsfeed-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-custom-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-external-page-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-notification-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-process-viewer-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-process-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-statistic-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: enhancement

#1007 IVYPORTAL-17519 Update dependencies to latest possible versions
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  Documentation/public-api/pom.xml
Labels: enhancement

#1053 IVYPORTAL-17649 Create sprint release > Fix GUI tests
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
Labels: enhancement

#1052 IVYPORTAL-17671 Adapt currentUserOrHisRolesAreInvolved API for Task
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/TaskService.java
  build/gui-test-new-dashboard/Jenkinsfile
Labels: bug

#1047 Bug/ivyportal 17273 wait manipulate expiry in task detail in portal doesn t produce correct behaviour 10
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDetailsTest.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemGeneralInfo/TaskItemGeneralInfoProcess.p.json
Labels: bug

#1059 IVYPORTAL-17273 Manipulate expiry in task detail in portal doesn't pr…
  AxonIvyPortal/PortalTest/src_test/portal/guitest/test/TaskDetailsTest.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemGeneralInfo/TaskItemGeneralInfoProcess.p.json
Labels: bug

#1055 IVYPORTAL-17671 Adapt currentUserOrHisRolesAreInvolved API for Task
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/TaskService.java
Labels: bug

#1010 IVYPORTAL-17408 DB query for filter in task/case widget is executed 3…
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseDashboardWidget/CaseDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessDashboardWidget/ProcessDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskDashboardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: bug

#1057 IVYPORTAL-17670 Missing DE translation locale LE: update translations
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
Labels: enhancement

#1049 IVYPORTAL-17669-Case-Details-DataTable-paginator-typo_RELEASE_LE
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
Labels: enhancement

#1041 IVYPORTAL-17427 Remove old statistics document
  Documentation/portal-guide/source/portal-developer-guide/components/additional-components.rst
  Documentation/portal-guide/source/portal-developer-guide/customization/default-chart-colors.rst
  Documentation/portal-guide/source/portal-developer-guide/customization/default-chart.rst
  Documentation/portal-guide/source/portal-developer-guide/customization/index.rst
  Documentation/portal-guide/source/portal-developer-guide/customization/menu.rst
  Documentation/portal-guide/source/portal-developer-guide/customization/portal-style-customization-logos-colors-date-patterns.rst
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
  Documentation/portal-guide/source/portal-developer-guide/permissions/index.rst
  Documentation/portal-guide/source/portal-developer-guide/settings/index.rst
  Documentation/portal-guide/source/portal-user-guide/accessibility/documents/shortcuts.csv
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
  Documentation/portal-guide/source/portal-user-guide/admin-settings/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-statistic-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/index.rst
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
  Documentation/portal-guide/source/portal-user-guide/portal-header/index.rst
Labels: documentation

#1069 IVYPORTAL-17670 Missing DE translation locale LE: update cms
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
Labels: enhancement

#1056 IVYPORTAL-17670 Missing DE translation locale 10: update translations
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
Labels: enhancement

#1075 Update index.rst
  Documentation/portal-guide/source/portal-user-guide/portal-multi-language/index.rst
Labels: skip-changelog

#1066 IVYPORTAL-17567 Homepage Selection leads to empty Page with misleadin…
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/configuration/CustomSubMenuItem.java
  AxonIvyPortal/portal/src/com/axonivy/portal/service/CustomSubMenuItemService.java
  Showcase/portal-developer-examples/cms/cms_de.yaml
  Showcase/portal-developer-examples/cms/cms_en.yaml
  Showcase/portal-developer-examples/cms/cms_es.yaml
  Showcase/portal-developer-examples/cms/cms_fr.yaml
  Showcase/portal-developer-examples/processes/Functional Processes/CustomLoadSubMenuItems.p.json
Labels: bug

#1067 IVYPORTAL-17567 Homepage Selection leads to empty Page with misleadin…
  AxonIvyPortal/portal/src/com/axonivy/portal/service/CustomSubMenuItemService.java
  Showcase/portal-developer-examples/cms/cms_de.yaml
  Showcase/portal-developer-examples/cms/cms_en.yaml
  Showcase/portal-developer-examples/cms/cms_es.yaml
  Showcase/portal-developer-examples/cms/cms_fr.yaml
  Showcase/portal-developer-examples/processes/Functional Processes/CustomLoadSubMenuItems.p.json
Labels: bug

#1074 IVYPORTAL-17529: implement shortcut for task case process list
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1085 IVYPORTAL-17670 Missing DE translation locale LE: add new translation
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
Labels: enhancement

#1088 IVYPORTAL-17534: Put descriptive information of the Case/Task
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/StartCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
Labels: enhancement

#1089 cicd-fix-fail-GUI_test_LE
  AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/Showcases.p.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/MenuTest.java
Labels: enhancement

#1086 feature/IVYPORTAL-17713-Cannot-focus-on-global-quick-search-LE
  AxonIvyPortal/portal/webContent/resources/js/global-search.js
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1090 IVYPORTAL-17720 Task list widget sort by created date does not work
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
Labels: enhancement
