Repository axonivy-market/portal, pull requests merged in 2024-10, with the labels that each got.

#1083 IVYPORTAL-17702 Remove obsoleted images from Portal document
  Documentation/portal-guide/source/portal-user-guide/full-task-list/how-to-reset-to-default.png
  Documentation/portal-guide/source/portal-user-guide/full-task-list/how-to-switch-to-edit-mode.png
  Documentation/portal-guide/source/portal-user-guide/full-task-list/how-to-switch-to-view-mode.png
Labels: enhancement

#1105 IVYPORTAL-17732-Change-elastic-search-to-open-search
  AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/CreateDataForComplexFilter.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/statistics/ClientStatisticResponse.java
  AxonIvyPortal/portal/src/com/axonivy/portal/rest/ClientStatisticRestService.java
  AxonIvyPortal/portal/src/com/axonivy/portal/service/ClientStatisticService.java
Labels: enhancement

#1084 Feature/ivyportal 17546 UI facelift for lts 12.0.0
  AxonIvyPortal/portal-components/cms/Images/process/PROCESSMODELING.svg
  AxonIvyPortal/portal-components/cms/Images/process/PROCESSMODELINGDARK.svg
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessWidgetPage.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/images/WelcomeWidget/DefaultImage.jpg
  AxonIvyPortal/portal/cms/images/WelcomeWidget/DefaultImageDark.jpg
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bo/ExternalLinkProcessItem.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bo/IvyProcess.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/process/DashboardProcess.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DefaultImage.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/CombinedModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/ImageModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/Filter/Filter.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessImageMode.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessGridItem/ProcessGridItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/CardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-dark.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
  AxonIvyPortal/portal/webContent/resources/css/utility.css
  AxonIvyPortal/portal/webContent/resources/js/client-statistic.js
  AxonIvyPortal/portal/webContent/resources/js/process-widget.js
Labels: enhancement

#1107 IVYPORTAL-16535: Update doc - only run one portal per security contex…
  Documentation/portal-guide/source/portal-developer-guide/architecture/index.rst
Labels: enhancement

#1095 Ivyportal -17687-showing-flaky-test-on-result-LE
  AxonIvyPortal/portal-selenium-test/resources/extractFlakyTests.sh
  build/gui-test-new-dashboard/Jenkinsfile
Labels: enhancement

#1117 IVYPORTAL-17533 create accessibility mode dashboard template for LE: …
  AxonIvyPortal/portal-selenium-test/resources/css/document-screenshot.css
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-case-widget-has-quicksearch.json
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-task-widget-has-quicksearch.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/ScreenshotUtils.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardConfigurationScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AbstractPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
  AxonIvyPortal/portal/processes/Functional Processes/AccessibilityShortcutCustomWidget.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/Dashboard.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/AccessibilityShortcut/AccessibilityShortcut.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/AccessibilityShortcut/AccessibilityShortcutData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/AccessibilityShortcut/AccessibilityShortcutProcess.p.json
  AxonIvyPortal/portal/webContent/layouts/frame-10.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/progress-loader.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/resources/css/accessibility.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-dark.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
Labels: enhancement

#1131 Feature/ivyportal 17533 create accessibility mode dashboard template le
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
Labels: enhancement

#1138 IVYPORTAL-17815: Add custom field column style
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/AbstractColumn.java
Labels: enhancement

#1134 feature/IVYPORTAL-17763-Display-Case-custom-field-on-Task-widget-LE
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
Labels: bug, enhancement

#1135 IVYPORTAL-17763: Fix display case customfield on task widget
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
Labels: bug

#1129 IVYPORTAL-17785: Update Add new configuration UI
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NewsWidgetConfiguration/NewsWidgetConfiguration.xhtml
Labels: enhancement

#1145 IVYPORTAL-17795: Change default target for ENTER on filter dialog
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: enhancement

#1096 Feature/ivyportal 17539 implement column width changing for portal widgets version 10
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/AbstractColumn.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/ActionsColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/ApplicationColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CategoryColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CreatedDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CreatorColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/DescriptionColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/FinishedDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/IdColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/NameColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/OwnerColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/StateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/process/ApplicationColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ActionsColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ApplicationColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/CategoryColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/CreatedDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/DescriptionColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ExpiryDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/IdColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/NameColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/PriorityColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ResponsibleColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/StartColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/StateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/StartCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
Labels: enhancement

#1106 IVYPORTAL-17539 Implement column width changing for portal widgets - …
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: documentation

#1144 Feature/ivyportal 17770 UI facelift for lts 12.0.0 part 3
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardModificationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ReorderDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardProcessWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardSupportMultiLanguageTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetFilterTest.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/AbstractProcessBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/process/DashboardProcess.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardConfiguration/PortalDashboardConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/ImageModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessGridItem/ProcessGridItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/ShareLinkDialog/ShareLinkDialog.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
  AxonIvyPortal/portal/webContent/layouts/decorator/portal-dialog-with-icon.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/includes/WidgetFilter.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-dark.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
  Showcase/portal-user-examples/src/com/axonivy/portal/userexamples/bean/ExampleHomeBean.java
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/ExampleHomePage/ExampleHomePage.xhtml
Labels: enhancement

#1126 IVYPORTAL-17768: Adapt Put descriptive information of the Case/Task
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/ActionsCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/StartCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
Labels: enhancement

#1149 IVYPORTAL-17533 Create Accessibility Mode Dashboard Template
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1133 IVYPORTAL-17707 Provide No-Code Configurations for the IFrame Task Template in the Neo Designer
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/IFrameTaskConfig/IFrameTaskConfig.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/IFrameTaskConfig/IFrameTaskConfigData.d.json
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/IFrameTaskConfig/IFrameTaskConfigProcess.p.json
  AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml
  Documentation/portal-guide/source/portal-developer-guide/customization/business-details-page.rst
  Documentation/portal-guide/source/portal-developer-guide/customization/images/business-details-page/customization-business-details-page-iframe.png
  Documentation/portal-guide/source/portal-developer-guide/iframe/documents/available_other_options.csv
  Documentation/portal-guide/source/portal-developer-guide/iframe/documents/available_process_steps_options.csv
  Documentation/portal-guide/source/portal-developer-guide/iframe/index.rst
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
  Showcase/InternalSupport/src_hd/internaltest/ui/SaleDepartment/SaleDepartment.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/CustomizedDocumentTableExample/CustomizedDocumentTableExample.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/DocumentTableExample/DocumentTableExample.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/InvestmentRequestBusinessDetailsPage/InvestmentRequestBusinessDetailsPage.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/leaverequest/LeaveRequestApproval/LeaveRequestApproval.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/leaverequest/LeaveRequestCreation/LeaveRequestCreation.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/leaverequest/LeaveRequestSummary/LeaveRequestSummary.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/showcase/PhotoLibraryOfDefaultProcessImageExample/PhotoLibraryOfDefaultProcessImageExample.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/Approve/Approve.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/CreateInvestment/CreateInvestment.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/CustomParamsForIFrame/CustomParamsForIFrame.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/CustomTaskNameForIFrame/CustomTaskNameForIFrame.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/EmployeeDetailsInFrame/EmployeeDetailsInFrame.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/EmployeeSearchInFrame/EmployeeSearchInFrame.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/LeaveRequestForm/LeaveRequestForm.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/NewPayment/NewPayment.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/Review/Review.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/TemplateExampleInFrame/TemplateExampleInFrame.xhtml
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/leaverequest/LeaveRequestApproval/LeaveRequestApproval.xhtml
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/leaverequest/LeaveRequestCreation/LeaveRequestCreation.xhtml
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/leaverequest/LeaveRequestSummary/LeaveRequestSummary.xhtml
Labels: enhancement

#1152 feature/IVYPORTAL-17777-add-cancel-button-for-complex-filter-diallog
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/SidebarWidgetConfiguration.xhtml
  AxonIvyPortal/portal/webContent/resources/js/sidebar-widget-configuration.js
Labels: enhancement

#1162 feature/IVYPORTAL-17764-Only-defined-shoutcuts-are-effected-LE
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1161 Feature/ivyportal 17461 remove full task list and replace it with the task widget ver5
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuItem.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuNavigator.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageMapper.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageType.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/navigation/PortalNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1130 IVYPORTAL-17540 Implement column width changing for portal widgets - LE
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardModificationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCaseWidgetTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/AbstractColumn.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/ActionsColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/ApplicationColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CategoryColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CreatedDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CreatorColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/DescriptionColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/FinishedDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/IdColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/NameColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/OwnerColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/StateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/process/ApplicationColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ActionsColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ApplicationColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/CategoryColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/CreatedDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/DescriptionColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ExpiryDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/IdColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/NameColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/PriorityColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ResponsibleColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/StartColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/StateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseDashboardWidget/CaseDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/StartCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
Labels: enhancement

#1166 IVYPORTAL-17912 Fix invalid function startTaskFromNoti in Notification Full Page
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/NotificationBean.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/NotificationFullPage/NotificationFullPage.xhtml
Labels: enhancement

#1170 IVYPORTAL-17540 Implement column width changing for portal widgets: f…
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/WidgetFilterService.java
Labels: enhancement

#1171 Feature/ivyportal 17461 remove full task list and replace it with the task widget ver5
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/config/variables/Portal/TaskTemplateDashboard.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuNavigator.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageMapper.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/navigation/PortalNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/SessionAttribute.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/UserUtils.java
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1167 IVYPORTAL-17829 Use Portal view expire exception dialog inside task iframe
  AxonIvyPortal/PortalKitTestHelper/webContent/layouts/includes/exception.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/portalException.xhtml
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
  AxonIvyPortal/portal/webContent/resources/js/session-warning.js
  Documentation/portal-guide/source/portal-developer-guide/components/error-handling.rst
  Showcase/portal-components-examples/webContent/layouts/includes/exception.xhtml
  Showcase/portal-developer-examples/webContent/layouts/includes/exception.xhtml
  Showcase/portal-user-examples/webContent/layouts/includes/exception.xhtml
Labels: enhancement

#1174 IVYPORTAL-17900: Make file upload size limit configurable
  AxonIvyPortal/portal-components/processes/Functional Processes/UploadDocumentItem.p.json
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/DocumentUploadBean.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableData.d.json
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  Documentation/portal-guide/source/portal-components/documents/document_table_component_attributes.csv
  Showcase/portal-components-examples/processes/Functional Processes/CustomDocumentFeatures.p.json
Labels: enhancement
