Repository axonivy-market/portal, pull requests merged in 2024-08, with the labels that each got.

#941 Feature/ivyportal 16892 hide case creator info
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuNavigator.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/chat/ChatService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ChatRendererBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/StatisticBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserProfileBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/AbstractConfigurableContentBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/AvatarBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardStatisticChartBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/PortalExceptionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/StatisticChartCreationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskAnalysisWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/VisibilityBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/casefilter/impl/DefaultCaseFilterContainer.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/CaseLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/TaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/internal/RelatedCaseLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CaseColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CreatorColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/CaseExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardCaseSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/CaseDocumentService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/DateTimeGlobalSettingService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/GlobalSettingService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/IFrameService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/GrowlMessageUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/ThemeBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/AbstractCaseWidgetFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/UploadDocumentUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/PortalCaseListInFrame/PortalCaseListInFrame.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseNoteHistory/CaseNoteHistory.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalCases/PortalCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemGeneralInformation/CaseItemGeneralInformation.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseListHeader/CaseListHeader.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskAnalysisWidget/StatisticResult.xhtml
  AxonIvyPortal/portal/webContent/layouts/PortalCasesTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/SearchResultsTemplate.xhtml
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: feature

#903 feature/IVYPORTAL-16862-Announcement-cannot-be-change-when-already-enable-LE
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/AnnouncementService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettings.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettingsProcess.p.json
Labels: enhancement

#962 MARP-620 Add release-drafter workflow
  .github/workflows/publish-release.yml
  .github/workflows/release-drafter.yml
Labels: enhancement, skip-changelog

#984 Document/ivyportal 17285 coded update document for setting up custom callable dialog to show how called process signature should look like lts
  Documentation/portal-guide/source/portal-developer-guide/customization/business-details-page.rst
Labels: skip-changelog

#987 IVYPORTAL-17391 Wrong language message after session is killed
  AxonIvyPortal/portal/webContent/layouts/includes/portalException.xhtml
Labels: bug

#992 Update LanguageService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/LanguageService.java
Labels: skip-changelog

#993 Update LanguageService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/LanguageService.java
Labels: skip-changelog

#994 IVYPORTAL-17402 Improve visualization of numbers - Add delimiter for big numbers
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseDashboardWidget/CaseInfo.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessDashboardWidget/ProcessInfo.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskInfo.xhtml
Labels: enhancement

#995 IVYPORTAL-17524 Update version from 11.4 to 11.4.0 in dashboard templ…
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
Labels: enhancement
