Repository axonivy-market/portal, pull requests merged in 2024-12, with the labels that each got.

#1286 Updated all pom build.plugin.version=12.0.0-SNAPSHOT, ivy.engine.vers…
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1289 IVYPORTAL-18045-Check-and-beautify-screenshot-MASTER
  AxonIvyPortal/portal-selenium-test/resources/css/document-screenshot.css
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/HandleErrorPageScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/SettingScreenshotTest.java
  Documentation/portal-guide/source/portal-user-guide/admin-settings/index.rst
Labels: enhancement

#1109 IVYPORTAL-17542-Use-latest-web-tester-to-run-all-tests
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/ComplexFilterHelper.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AbsencePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ChatPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardNewsWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/LeaveRequestIFramePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/LeaveRequestPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NoteHistoryPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ReorderDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/RoleManagementPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/SearchResultPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskIFrameTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/WelcomeEditWidgetNewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardRestoreConfigurationTest.java
Labels: enhancement

#1285 Document/ivyportal 17805 update documentation for i frame task template configuration
  AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml
  Documentation/portal-guide/source/portal-developer-guide/iframe/index.rst
Labels: documentation

#1288 feature/IVYPORTAL-18064-Adapt-github-release-note-template-to-the-same-with-release-drafter-and-update-Create-Portal-release-page
  .github/release.yml
Labels: enhancement

#1292 Feature/ivyportal 18039 write tests for highlighting menu with navigation
  AxonIvyPortal/portal-selenium-test/resources/testFile/complex-dashboard.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/MainMenuPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/MenuHighlightTest.java
Labels: skip-changelog

#1291 IVYPORTAL-18054 Iframe task template: Missing permission check for Case information
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/AbstractTaskTemplateBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseWidgetBean.java
  AxonIvyPortal/portal/webContent/layouts/restricted/AbstractTaskTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
Labels: enhancement

#1293 Release 12.0.1
  Documentation/maven/pom.xml
Labels: skip-changelog

#1298 feature/IVYPORTAL-18028-High-Failure-to-use-HTTPS-or-SFTP-URL-in-Mave…
  AxonIvyPortal/portal-product/pom.xml
Labels: enhancement

#1305 feature/IVYPORTAL-18028-High-Failure-to-use-HTTPS-or-SFTP-URL-in-Mave…
  AxonIvyPortal/portal-product/pom.xml
Labels: enhancement

#1307 IVYPORTAL-18029 High - Client-side cross-site scripting
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/IFrameTaskTemplateBean.java
  AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/js/iframe-task-template.js
Labels: enhancement

#1310 IVYPORTAL-18029: Security findings- Client-side cross-site scripting
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/IFrameTaskTemplateBean.java
  AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/js/iframe-task-template.js
Labels: enhancement

#1316 Feature/ivyportal 18029 high client side cross site scripting 12
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/LanguageSettingTest.java
Labels: enhancement

#1300 IVYPORTAL-18072 SPIKE: Evaluate the full screen issue with new case a…
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/Dashboard.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
  AxonIvyPortal/portal/webContent/resources/js/responsive-toolkit.js
Labels: bug

#1301 IVYPORTAL-18063-bring-back-default-sort-for-task-case-widget-LE
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditCaseWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditTaskWidgetTest.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  build/document-screenshot-selenide/Jenkinsfile
Labels: enhancement

#1319 IVYPORTAL-18063-bring-back-default-sort-for-task-case-widget-LE (#1301)
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditCaseWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditTaskWidgetTest.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  build/document-screenshot-selenide/Jenkinsfile
Labels: enhancement

#1311 Feature/ivyportal 18032 UI facelift conflict
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalCasesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalProcessesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseDocuments/CaseDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardDetailModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/AbsenceManagement.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettings.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/IconSelection/IconSelection.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/WarningBeforeLeavingTask/WarningBeforeLeavingTask.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-dark.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
  AxonIvyPortal/portal/webContent/resources/css/utility.css
  AxonIvyPortal/portal/webContent/resources/js/process-widget.js
  Documentation/portal-guide/source/portal-user-guide/full-process-list/index.rst
Labels: enhancement

#1309 feature/IVYPORTAL-18068 Update test data of performance test engine
  AxonIvyPortal/PortalKitTestHelper/dataclasses/portalKit_test/DataCreationData.d.json
  AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/DataCreation.p.json
Labels: skip-changelog

#1318 feature/IVYPORTAL-18035-Failure-to-use-secure-cookies
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CookieHelper.java
Labels: enhancement

#1317 feature/IVYPORTAL-18034-Information-exposure-through-an-error-message
  AxonIvyPortal/portal/src/com/axonivy/portal/rest/GlobalSearchRestService.java
Labels: enhancement

#1323 feature/IVYPORTAL-18035-Failure-to-use-secure-cookies
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CookieHelper.java
Labels: enhancement

#1327 feature/IVYPORTAL-18034-Information-exposure-through-an-error-message…
  AxonIvyPortal/portal/src/com/axonivy/portal/rest/ChatBotRestService.java
Labels: enhancement

#1296 IVYPORTAL-18067 Create Portal branch release/12.0
  AxonIvyPortal/PortalApp/.project
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/.project
  AxonIvyPortal/portal-product/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Documentation/maven/.project
  Documentation/maven/pom.xml
  Documentation/portal-guide/.project
  Documentation/public-api/.project
  Documentation/public-api/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-demo-app/.project
  Showcase/portal-demo-app/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
  build/ci/Jenkinsfile
  build/create-release/Jenkinsfile
  build/document-screenshot-selenide/Jenkinsfile
  build/gui-test-new-dashboard/Jenkinsfile
  build/integration/Jenkinsfile
  build/performance-test/Jenkinsfile
  build/update-pom/Jenkinsfile
  build/upgrade-engine/Jenkinsfile
Labels: enhancement

#1297 feature/IVYPORTAL-18067-Create-Portal-branch-release-12.0-LE
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-product/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Documentation/maven/pom.xml
  Documentation/public-api/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-demo-app/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
  build/create-release/Jenkinsfile
  build/document-screenshot-selenide/Jenkinsfile
  build/gui-test-new-dashboard/Jenkinsfile
  build/integration/Jenkinsfile
  build/performance-test/Jenkinsfile
  build/update-pom/Jenkinsfile
Labels: enhancement

#1324 feature/IVYPORTAL-18073-Create-file-preview-for-PDF-.log-and-PNG-master
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/Variable.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalCasesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/UploadDocumentTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseTaskDocumentBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsData.d.json
  AxonIvyPortal/portal/webContent/resources/css/module.css
Labels: enhancement

#1333 Update pom.xml
  Documentation/maven/pom.xml
Labels: skip-changelog

#1320 IVYPORTAL-18153 Fix GUI tests
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskIFrameTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/BackNavigationTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetFilterTest.java
Labels: skip-changelog

#1334 Update Jenkinsfile
  build/performance-test/Jenkinsfile
Labels: skip-changelog

#1338 Update Dockerfile
  build/Dockerfile
Labels: skip-changelog

#1340 Bug/ivyportal 18205 fix build performance master
  build/Dockerfile
  build/performance-test/Dockerfile
Labels: skip-changelog

#1350 IVYPORTAL-18153 Fix GUI tests (#1320)
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskIFrameTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/BackNavigationTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetFilterTest.java
Labels: enhancement

#1354 IVYPORTAL-18222: Fixed notification screenshot test
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/NotificationScreenshotTest.java
Labels: enhancement

#1355 IVYPORTAL-18222: Fixed notification screenshot test (#1354)
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/NotificationScreenshotTest.java
Labels: enhancement

#1359 Update pom.xml for documentation release S269
  Documentation/maven/pom.xml
Labels: skip-changelog

#1360 Revert "Update pom.xml for documentation release S269"
  Documentation/maven/pom.xml
Labels: skip-changelog

#1353 Feature/ivyportal 14419 raise version of your portal maven artifacts to the next development cycle after release
  build/create-release/Jenkinsfile
  build/update-pom/Dockerfile
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1363 IVYPORTAL-14419 Raise version of your portal maven artifacts to the n…
  build/update-pom/Dockerfile
  build/update-pom/Jenkinsfile
Labels: enhancement, skip-changelog

#1362 Feature/ivyportal 14419 raise version of your portal maven artifacts to the next development cycle after release v10
  build/create-release/Jenkinsfile
  build/update-pom/Dockerfile
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1361 IVYPORTAL-14419 Raise version of your portal maven artifacts to the n…
  build/create-release/Jenkinsfile
  build/update-pom/Dockerfile
  build/update-pom/Jenkinsfile
Labels: skip-changelog
