Repository axonivy-market/portal, pull requests merged in 2024-11, with the labels that each got.

#1175 Feature/ivyportal 17461 remove full task list and replace it with the task widget ver5
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/SessionAttribute.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/MainMenuPage.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/config/variables/Portal/DefaultTaskListDashboard.json
  AxonIvyPortal/portal/dataclasses/ch/ivy/addon/portal/generic/PortalStartData.d.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuItem.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuNavigator.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/TaskSubMenuItem.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageMapper.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageType.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/navigation/PortalNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/TaskEndInfo.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/Dashboard.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/MenuKind.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/PortalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/SessionAttribute.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardAsMenu/PortalDashboardAsMenuData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalMainDashboard/PortalMainDashboard.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalMainDashboard/PortalMainDashboardData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalMainDashboard/PortalMainDashboardProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/UserProfile/UserProfile.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1120 IVYPORTAL-17731 Create accessibility documentation: update document
  Documentation/portal-guide/source/portal-user-guide/accessibility/index.rst
Labels: documentation

#1183 Feature/ivyportal 17461 remove full task list and replace it with the task widget ver5
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/config/variables/Portal/DefaultTaskListDashboard.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultTaskListDashboardUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
Labels: enhancement

#1182 IVYPORTAL-17829 Use Portal view expire exception dialog inside task i…
  AxonIvyPortal/PortalKitTestHelper/webContent/layouts/includes/exception.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/portalException.xhtml
  AxonIvyPortal/portal/webContent/resources/js/session-warning.js
  Documentation/portal-guide/source/portal-developer-guide/components/error-handling.rst
  Showcase/portal-components-examples/webContent/layouts/includes/exception.xhtml
  Showcase/portal-developer-examples/webContent/layouts/includes/exception.xhtml
  Showcase/portal-user-examples/webContent/layouts/includes/exception.xhtml
Labels: enhancement

#1185 Feature/ivyportal 17461 remove full task list and replace it with the task widget ver5
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/Variable.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/AdminSettingsTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskWidgetTest.java
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserProfileBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/TaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultTaskListDashboardUtils.java
Labels: enhancement

#1189 IVYPORTAL-17461 Remove Full Task List and Replace it with the Task Wi…
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1190 IVYPORTAL-17944 Fix bug Portal.DateTimeFormat.DateFilterWithTime import not working
  AxonIvyPortal/portal/src/com/axonivy/portal/dto/dashboard/filter/DashboardFilter.java
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
Labels: enhancement, skip-changelog

#1192 IVYPORTAL-17855 Various or urgent requests in IVYPORTAL - S267 > IVYP…
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/css/utility.css
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
Labels: bug, enhancement

#1193 Feature/ivyportal 17461 remove full task list and replace it with the task widget ver5
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuNavigator.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/navigation/PortalNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/UserProperty.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/UserSettingService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultTaskListDashboardUtils.java
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1197 Feature/ivyportal 17461 remove full task list and replace it with the task widget ver5
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/DashboardImportBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
Labels: enhancement

#1191 IVYPORTAL-17822-LTS-Testing-Buffer-Story-Portal-return-null-when-clea…
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
Labels: skip-changelog

#1194 IVYPORTAL-17822-LTS-Testing-Buffer-Story-update-welcome-image
  AxonIvyPortal/portal/webContent/resources/images/welcome-widget-sample.png
Labels: skip-changelog

#1186 IVYPORTAL-17947 Remove accessibility property in dashboard template LE
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/Dashboard.java
Labels: enhancement

#1206 IVYPORTAL-17978 Bug custom field column width auto resize
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/AbstractColumn.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: bug

#1208 feature/change-engine-version - Update version back to nightly-12.0
  build/create-release/Jenkinsfile
  build/document-screenshot-selenide/Jenkinsfile
  build/gui-test-new-dashboard/Jenkinsfile
  build/integration/Jenkinsfile
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1156 IVYPORTAL-17721 Quick search UI/UX behavior not perfect
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/GlobalSearch/GlobalSearch.xhtml
Labels: enhancement

#1150 feature/IVYPORTAL-17679-UI-Facelift-for-LTS-12.0.0-Part-2
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/UserSelection/UserSelection.xhtml
  AxonIvyPortal/portal-components/webContent/resources/css/user-selection-component.css
  AxonIvyPortal/portal-selenium-test/.settings/ch.ivyteam.ivy.designer.prefs
  AxonIvyPortal/portal-selenium-test/dataclasses/ch/ivyteam/ivy/project/portal/test/Data.d.json
  AxonIvyPortal/portal-selenium-test/dataclasses/ch/ivyteam/ivy/project/portal/test/Responsible.d.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AbsencePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AdminSettingsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AnnouncementPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardNewsWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewAbsencePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/UserProfilePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/AnnouncementTest.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bo/ExternalLinkProcessItem.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardConfiguration/PortalDashboardConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/Absence.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/AbsenceManagement.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/SelectDeputy.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/PortalManagement/PortalManagement.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/UserProfile/UserProfile.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettings.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettingsProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/IconSelection/IconSelection.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/PasswordValidation/PasswordValidation.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProjectVersion/ProjectVersion.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/RoleManagement/RoleManagement.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/WarningBeforeLeavingTask/WarningBeforeLeavingTask.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/WarningBeforeLostSession/WarningBeforeLostSession.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/multiapp/settings/PasswordSetting/PasswordSetting.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NewsWidget/ManageNews.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NewsWidget/NewsItem.xhtml
  AxonIvyPortal/portal/webContent/layouts/decorator/portal-dialog-with-icon.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/portalException.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-dark.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
  AxonIvyPortal/portal/webContent/resources/css/template.css
Labels: enhancement

#1215 feature/IVYPORTAL-17679-Facelift-handle-feedback - split column, light color dragdrop icon
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettings.xhtml
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-dark.css
Labels: skip-changelog

#1204 Feature/ivyportal 17461 remove full task list and replace it with the task widget ver5
  AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/GrantPermissions.p.json
  AxonIvyPortal/portal-selenium-test/jmeter/configuration/variables.Portal.Dashboard.json
  AxonIvyPortal/portal-selenium-test/jmeter/portal_walkthrough_testplan.jmx
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/NavigationHelper.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/ChatScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DemoProcessesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalTaskScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/GlobalGrowlIframeTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/LeaveRequestPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/MainMenuPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskIFrameTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/AdminSettingsTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/AvatarTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/BackNavigationTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/ChatTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/DateTimeDisplayTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/DisabledUserTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EnhanceVisibilityTasksForMemberOfRoleTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EscalationTaskTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/GlobalGrowlTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/LanguageSettingTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/LeaveRequestTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/MenuTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/PageRefreshingTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/PortalPermissionTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/ProcessInformationTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/ProcessViewerTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/ShowCaseNoteHistoryTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/ShowTaskNoteHistoryTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/SideStepTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/StickyNavigationDashboardTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/SystemNoteVisibilityTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/UploadDeleteDocumentVisibilityTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/BusinessCaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardRestoreConfigurationTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/globalsearch/SearchProcessTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/BehaviourWhenClickingOnTaskLineTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/CustomTaskDelegateTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskActionTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskCategoryMenuTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDescriptionChangeTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDetailsTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskFilterTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskPriorityChangeTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskTemplateIFrameTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskTemplateTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/userexample/test/CaseMapTest.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
Labels: enhancement

#1226 Feature/ivyportal 18000 fix g UI test le
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/FullProcessPageTest.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidgetConfiguration/CaseWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidgetConfiguration/TaskWidgetConfiguration.xhtml
Labels: skip-changelog

#1209 IVYPORTAL-17978: Bug custom field column width auto resize
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/AbstractColumn.java
Labels: enhancement

#1214 bug/IVYPORTAL-17899-Complex-filter-error-when-closing-filter-form-with-null-filter-LE
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/CaseDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/TaskDashboardWidget.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/TaskWidgetUserFilterBean.java
Labels: bug

#1231 IVYPORTAL-18011 Create accessibility documentation for LE
  Documentation/portal-guide/source/portal-user-guide/accessibility/index.rst
Labels: enhancement

#1216 feature/IVYPORTAL-17987-Dashboard-configuration-improvements-LE
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/ivydata/bo/JsonVersion.java
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/CaseDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/TaskDashboardWidget.java
Labels: enhancement

#1235 Update DefaultTaskListDashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultTaskListDashboardUtils.java
Labels: skip-changelog

#1229 bug/IVYPORTAL-17994-Permission-disappear-after-deleting-in-Dashboard-…
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
Labels: enhancement

#1224 Bug/IVYPORTAL-17531-Warning-logs-appear-in-console-if-running-process…
  AxonIvyPortal/PortalKitTestHelper/src_hd/ch/ivy/addon/portalkit/test/DataCreation/DataCreation.xhtml
  AxonIvyPortal/PortalKitTestHelper/webContent/layouts/frame-10.xhtml
Labels: skip-changelog

#1240 Merge 10.0.24.2 to the branch release/10.0
  AxonIvyPortal/PortalTest/pom.xml
  AxonIvyPortal/portal/pom.xml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/AbstractColumn.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/ActionsColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/ApplicationColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CategoryColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CreatedDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CreatorColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/DescriptionColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/NameColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/OwnerColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/StateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ActionsColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ApplicationColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/CategoryColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/CreatedDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/DescriptionColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ExpiryDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/IdColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/NameColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/PriorityColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ResponsibleColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/StartColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/StateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardColumnType.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
Labels: skip-changelog

#1220 IVYPORTAL-17725: Multiple headers are highlighted after sort
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
Labels: enhancement

#1241 IVYPORTAL-18005 UI facelift bug
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/WarningBeforeLeavingTask/WarningBeforeLeavingTask.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/multiapp/settings/LogoutSetting/LogoutSetting.xhtml
  AxonIvyPortal/portal/webContent/layouts/decorator/portal-dialog-with-icon.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/css/portal-root-variables.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-dark.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
  AxonIvyPortal/portal/webContent/resources/css/template.css
Labels: enhancement

#1239 Bug/ivyportal 17531 warning logs appear in console if running process create test data with category 10
  AxonIvyPortal/PortalKitTestHelper/src_hd/ch/ivy/addon/portalkit/test/DataCreation/DataCreation.xhtml
  AxonIvyPortal/PortalKitTestHelper/webContent/layouts/frame-10.xhtml
Labels: skip-changelog

#1246 IVYPORTAL-17982 Various or urgent requests in IVYPORTAL - S268
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardTaskWidgetBean.java
Labels: skip-changelog

#1245 Document/ivyportal 17422 remove full case list and replace it with the case widget dev guide
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
Labels: skip-changelog

#1225 feature/IVYPORTAL-17851-Upload-document-should-display-supporte…
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/css/portal-root-variables.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-dark.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
Labels: enhancement

#1243 feature/IVYPORTAL-17898-Apdat-case-owner-in-Portal
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCaseWidgetTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/OwnerColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/CaseDashboardExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/CaseSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/SecurityMemberDisplayNameUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemGeneralInformation/CaseItemGeneralInformation.xhtml
  Showcase/InternalSupport/processes/Business Processes/testProcesses/CaseOwner.p.json
Labels: enhancement

#1244 bug/IVYPORTAL-18015-Portal-meta-data-warning
  AxonIvyPortal/PortalKitTestHelper/webContent/layouts/OneComponent.xhtml
  AxonIvyPortal/PortalKitTestHelper/webContent/layouts/basic.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ForgotPassword/ForgotPassword.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/Login/Login.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PasswordReset/PasswordReset.xhtml
  AxonIvyPortal/portal/webContent/layouts/BasicTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/IFrameWithoutMenuTemplate.xhtml
Labels: skip-changelog

#1248 IVYPORTAL-17937 Accessibility Dashboard - Case widget column has a vertical dash
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
Labels: skip-changelog

#1253 Feature/ivyportal 17898 apdat case owner in portal
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/internal/RelatedTaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/CaseExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardCaseSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardProcessCaseSearchCriteria.java
Labels: enhancement

#1249 IVYPORTAL-17937 [Accessibility Dashboard] Case widget column has a vertical dash LE
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
Labels: enhancement

#1218 Feature/ivyportal 17525 check portal user documentation for lts 12.0.0 release
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardConfigurationScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/NotificationScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalCasesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalProcessesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NotificationCompactPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessWidgetPage.java
  AxonIvyPortal/portal/config/variables/Portal/ClientStatistic.json
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
  Documentation/portal-guide/source/portal-user-guide/admin-settings/index.rst
  Documentation/portal-guide/source/portal-user-guide/axon-ivy-portal/index.rst
  Documentation/portal-guide/source/portal-user-guide/complex-filter/index.rst
  Documentation/portal-guide/source/portal-user-guide/dashboard-configuration/index.rst
  Documentation/portal-guide/source/portal-user-guide/demo-processes/index.rst
  Documentation/portal-guide/source/portal-user-guide/forgot-password/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-case-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-process-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-task-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/includes/_common-icon.rst
  Documentation/portal-guide/source/portal-user-guide/includes/images/actions-menu.svg
  Documentation/portal-guide/source/portal-user-guide/includes/images/reorder.svg
  Documentation/portal-guide/source/portal-user-guide/index.rst
  Documentation/portal-guide/source/portal-user-guide/my-profile/index.rst
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
  Documentation/portal-guide/source/portal-user-guide/notification/index.rst
  Documentation/portal-guide/source/portal-user-guide/portal-chat/index.rst
  Documentation/portal-guide/source/portal-user-guide/portal-header/index.rst
  Documentation/portal-guide/source/portal-user-guide/portal-multi-language/index.rst
  Documentation/portal-guide/source/portal-user-guide/process-information/index.rst
  Documentation/portal-guide/source/portal-user-guide/qr-code/index.rst
  Documentation/portal-guide/source/portal-user-guide/statistic-chart/index.rst
Labels: enhancement

#1247 Bug/ivyportal 17918 bug notification bug some lines have no message and cause error when clicking start
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/NotificationBean.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/NotificationFullPage/NotificationFullPage.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NotificationWidget/NotificationWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/notification.xhtml
Labels: bug

#1251 IVYPORTAL-17527 Improve visualization of numbers - Add delimiter for big numbers
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseDashboardWidget/CaseInfo.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessDashboardWidget/ProcessInfo.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskInfo.xhtml
Labels: enhancement

#1258 IVYPORTAL-18018-verifying-UI-facelift-bug-pt2-fix-cms
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/multiapp/settings/LogoutSetting/LogoutSetting.xhtml
Labels: skip-changelog

#1255 IVYPORTAL-18018 UI facelift bug pt2
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/CompactModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
Labels: skip-changelog

#1250 IVYPORTAL-18022 Cannot export a dashboard that is not the last dashboard in public dashboards list in LE
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
Labels: skip-changelog

#1260 Feature/ivyportal 17422 remove full case list and replace it with the case widget 1
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/persistence/converter/BusinessEntityConverter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
Labels: skip-changelog

#1259 IVYPORTAL-17988 Try to migrate + add migration notes about resize col…
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-case-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-task-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/index.rst
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: documentation

#1233 feature/IVYPORTAL-18012-Adjust-width-for-default-templates-and-dashboard
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
Labels: enhancement

#1265 IVYPORTAL-17822 LTS Testing Buffer Story for Bugs and Fixes > IVYPORT…
  AxonIvyPortal/portal/dataclasses/portalkit/PortalCallableToolsData.d.json
  AxonIvyPortal/portal/dataclasses/portalkit/PortalToolsData.d.json
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/TaskWidgetUserFilterBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ai/FindCaseWidget/FindCaseWidgetData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ai/FindProcessWidget/FindProcessWidgetData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ai/FindTaskWidget/FindTaskWidgetData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskDashboardWidget.xhtml
Labels: bug

#1266 Update version to 12.0.0
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboard/converter/JsonDashboardConverterFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboard/converter/v120/DashboardProcessWidgetConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboardtemplate/converter/JsonDashboardTemplateConverterFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboardtemplate/converter/v120/DashboardTemplateProcessWidgetConverter.java
  Documentation/public-api/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1267 Bug/ivyportal 17918
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/UploadDocumentTest.java
Labels: skip-changelog

#1268 IVYPORTAL-17982 Various or urgent requests in IVYPORTAL - S268 > Adde…
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalCasesScreenshotTest.java
  Documentation/portal-guide/source/portal-developer-guide/introduction/index.rst
Labels: skip-changelog

#1269 feature/IVYPORTAL-18040-Update-user-doc-screenshot-change-doc
  Documentation/portal-guide/source/portal-user-guide/admin-settings/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-case-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-task-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/portal-header/index.rst
  Documentation/portal-guide/source/portal-user-guide/statistic-chart/index.rst
Labels: enhancement

#1272 Revert "Release 12.0.0"
  Documentation/maven/pom.xml
Labels: skip-changelog

#1270 feature/IVYPORTAL-18014-UserSetOwnPassword-permission-is-ignored-in-P…
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/processes/Functional Processes/ChangePassword.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/PermissionUtils.java
  Documentation/portal-guide/source/portal-user-guide/portal-header/index.rst
Labels: enhancement

#900 document/IVYPORTAL-17285-Update-document-for-setting-up-custom-Callab…
  Documentation/portal-guide/source/portal-developer-guide/dashboard/images/new-dashboard-case-widget/custom-action-button-custom-field-start.png
  Documentation/portal-guide/source/portal-developer-guide/dashboard/images/new-dashboard-case-widget/custom-action-destroy-case.png
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
  Documentation/portal-guide/source/portal-user-guide/portal-header/index.rst
Labels: documentation

#1279 Feature/ivyportal 18014 user set own password permission is ignored in portal with change password feature 10
  Documentation/portal-guide/source/portal-user-guide/portal-header/index.rst
Labels: skip-changelog

#1281 document/IVYPORTAL-17285-Update-document-for-setting-up-custom-Callab…
  Documentation/portal-guide/source/portal-user-guide/portal-header/index.rst
Labels: skip-changelog

#1261 IVYPORTAL-17571-Remove-unused-function-in-document-screenshot.js-10
  AxonIvyPortal/PortalTest/resources/js/document-screenshot.js
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
Labels: enhancement

#1262 IVYPORTAL-17571-Remove-unused-function-in-document-screenshot.js-MASTER
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
Labels: enhancement

#1282 IVYPORTAL-17938-Action-step-dropdown-so-bad-alignment
  AxonIvyPortal/portal/webContent/resources/css/module.css
Labels: enhancement
