Repository axonivy-market/portal, pull requests merged in 2025-10, with the labels that each got.

#2561 IVYPORTAL-19666 Update pom to 13.2.0-m281
  Documentation/maven/pom.xml
Labels: enhancement, skip-changelog

#2562 Revert "IVYPORTAL-19666 Update pom to 13.2.0-m281 (#2561)"
  Documentation/maven/pom.xml
Labels: enhancement, skip-changelog

#2403 IVYPORTAL-19239 Implement and Roll out Load Testing in Portal
  build/performance-jmeterdsl-test/Jenkinsfile
Labels: enhancement, feature

#2570 Translations update from Hosted Weblate
  Documentation/portal-guide/weblate/locale/ja/LC_MESSAGES/portal-developer-guide.po
Labels: skip-changelog

#2571 Translations update from Hosted Weblate
  Documentation/portal-guide/weblate/locale/ja/LC_MESSAGES/portal-user-guide.po
Labels: skip-changelog

#2504 IVYPORTAL-19625 Double scroll bars appearing in Task and Case tables
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: skip-changelog

#2502 IVYPORTAL-19625 Double scroll bars appearing in Task and Case tables
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: skip-changelog

#2503 IVYPORTAL-19625 Double scroll bars appearing in Task and Case tables
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: skip-changelog

#2581 Translations update from Hosted Weblate
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
Labels: skip-changelog

#2585 IVYPORTAL-19681 Fix testTriggerEscalationTaskOnRelatedTasksOfCase on master
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EscalationTaskTest.java
Labels: enhancement, skip-changelog

#2588 - Update Javax to Jakarta
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/chat/ChatService.java
Labels: skip-changelog

#2592 Translations update from Hosted Weblate
  Documentation/portal-guide/weblate/locale/ja/LC_MESSAGES/portal-user-guide.po
Labels: skip-changelog

#2501 IVYPORTAL-19354 Optimize embedInFrame handling in Portal
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/service/impl/ProcessService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/IFrameService.java
  AxonIvyPortal/portal/webContent/resources/js/iframe-task-template.js
  Documentation/portal-guide/source/portal-developer-guide/iframe/images/request-tab-embedInFrame.png
  Documentation/portal-guide/source/portal-developer-guide/iframe/index.rst
Labels: enhancement
