Repository axonivy-market/portal, pull requests merged in 2025-07, with the labels that each got.

#2205 IVYPORTAL-19194 Improve column headers in export and complex filter
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCaseWidgetFilterTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditCaseWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditTaskWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetFilterTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskWidgetTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/CaseDashboardExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/DashboardWidgetExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/AbstractCaseWidgetFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/AbstractTaskWidgetFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/CaseWidgetUserFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/TaskWidgetUserFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/dto/dashboard/filter/DashboardFilter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/AiToolUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/FilterField.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/FilterFieldFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/TaskFilterFieldFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldApplication.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldCategory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldCreatedDate.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldCreator.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldDescription.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldFinishedDate.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldId.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldName.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldState.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldApplication.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldCategory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldCreatedDate.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldDescription.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldExpiryDate.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldFinishedDate.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldId.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldName.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldPriority.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldResponsible.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldState.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseDashboardWidget/CaseDashboardWidgetProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/FieldAdd.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskDashboardWidgetProcess.p.json
Labels: enhancement

#2203 IVYPORTAL-19217 Update Github action for screenshots
  .github/workflows/portal-document-screenshot-test.yml
Labels: skip-changelog

#2204 IVYPORTAL-19217 Update Github action for screenshots
  .github/workflows/portal-document-screenshot-test.yml
Labels: skip-changelog

#2183 IVYPORTAL-19211 Improve document screenshot
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-has-one-number-chart.json
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-statistic-widget-demo.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/StatisticScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AdminSettingsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/RoleSelectionExample/RoleSelectionExample.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/UserSelectionExample/UserSelectionExample.xhtml
Labels: enhancement, skip-changelog

#2207 IVYPORTAL-19203 Quick search duplicate api call
  AxonIvyPortal/portal/webContent/resources/js/global-search.js
Labels: enhancement

#2184 bug/Improve-screenshot-test
  AxonIvyPortal/portal/webContent/resources/js/statistic.js
Labels: skip-changelog

#2210 IVYPORTAL-19203 Quick search duplicate api call LTS 12
  AxonIvyPortal/portal/webContent/resources/js/global-search.js
Labels: enhancement

#2134 IVYPORTAL-18996 Improve Column Management dialog
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/IMultiLanguage.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ExternalLinkBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DisplayNameConvertor.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/StatisticConfigurationBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/FieldAdd.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/MultiLanguageConfiguration/MultiLanguageConfiguration.xhtml
Labels: enhancement

#2136 IVYPORTAL-18996 Improve Column Management dialog
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/IMultiLanguage.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ExternalLinkBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DisplayNameConvertor.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/FieldAdd.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/MultiLanguageConfiguration/MultiLanguageConfiguration.xhtml
Labels: enhancement

#2211 IVYPORTAL-19212 Improve document screenshot
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DemoProcessesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ExampleOverviewPage.java
Labels: skip-changelog

#2221 IVYPORTAL-19307 Create sprint release > Update doc version
  Documentation/maven/pom.xml
Labels: skip-changelog

#2214 IVYPORTAL-19252 Improve aria label in Portal left menu
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement, skip-changelog

#2224 IVYPORTAL-19252 Improve aria label in Portal left menu
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement, skip-changelog

#2225 IVYPORTAL-19220 Improve document screenshot
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DemoProcessesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalCasesScreenshotTest.java
Labels: enhancement, skip-changelog

#2219 IVYPORTAL-19220 Improve document screenshot
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseMapPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/LeaveRequestPage.java
Labels: enhancement, skip-changelog

#2202 IVYPORTALl-18832 Automatically install the sample dashboard with the Portal User Example
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/UserProperty.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/UserExampleUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CustomWidgetConfiguration/CustomWidgetConfiguration.xhtml
  Showcase/portal-developer-examples/processes/Functional Processes/CustomLoadSubMenuItems.p.json
  Showcase/portal-user-examples/cms/cms_de.yaml
  Showcase/portal-user-examples/cms/cms_en.yaml
  Showcase/portal-user-examples/cms/cms_es.yaml
  Showcase/portal-user-examples/cms/cms_fr.yaml
  Showcase/portal-user-examples/cms/cms_ja.yaml
  Showcase/portal-user-examples/dataclasses/com/axonivy/portal/userexamples/CreateTestDataData.d.json
  Showcase/portal-user-examples/dataclasses/com/axonivy/portal/userexamples/UserExampleGuideData.d.json
  Showcase/portal-user-examples/processes/Business Processes/CreateTestData.p.json
  Showcase/portal-user-examples/processes/Start Processes/UserExampleGuide.p.json
  Showcase/portal-user-examples/src/com/axonivy/portal/userexamples/bean/NoteBean.java
  Showcase/portal-user-examples/src/com/axonivy/portal/userexamples/bean/TestDataCreationBean.java
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/CustomWidgetNote/CustomWidgetNote.xhtml
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/CustomWidgetNote/CustomWidgetNoteData.d.json
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/CustomWidgetNote/CustomWidgetNoteProcess.p.json
  variables.Portal.Dashboard.json
Labels: enhancement

#2228 Feature/ivyportal 18832 automatically install the sample dashboard with the portal user examples spike ver2
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
Labels: enhancement

#2229 Feature/ivyportal 18832 automatically install the sample dashboard with the portal user examples spike ver2
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
Labels: skip-changelog

#2231 Feature/ivyportal 18832 automatically install the sample dashboard with the portal user examples spike ver2
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/MenuTest.java
Labels: skip-changelog

#2232 IVYPORTAL-19301 Improve column management dialog
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
Labels: enhancement, skip-changelog

#2208 IVYPORTAL-19142 UI findings
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/Absence.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessListMode.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/SidebarWidgetConfiguration.xhtml
  AxonIvyPortal/portal/webContent/resources/css/portal.css
  AxonIvyPortal/portal/webContent/resources/js/notification.js
Labels: enhancement

#2238 IVYPORTAL-19142 UI findings
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/Absence.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessListMode.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/SidebarWidgetConfiguration.xhtml
  AxonIvyPortal/portal/webContent/resources/css/portal.css
  AxonIvyPortal/portal/webContent/resources/js/notification.js
Labels: skip-changelog

#2227 bug/IVYPORTAL-19248: Columns-field-disappear-in-dashboard-JSON-file-after-adding-new-field-in-widget
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
Labels: bug, enhancement

#2248 IVYPORTAL-19306 Fix unstable screenshot test
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/AdditionalComponentsScreenshotTest.java
Labels: skip-changelog

#2200 Feature/ivyportal 18926 show business business case detail in case detail 12
  AxonIvyPortal/portal-selenium-test/resources/testFile/custom-case-details.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/AbstractConfigurableContentBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/WidgetType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/widget/AbstractWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/widget/BusinessDetailsWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/CustomWidgetParam.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CustomWidgetUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/UrlUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/BusinessDetailsUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemBusinessDetails/CaseItemBusinessDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemBusinessDetails/CaseItemBusinessDetailsData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemBusinessDetails/CaseItemBusinessDetailsProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/webContent/resources/js/case-details.js
  Documentation/portal-guide/source/portal-developer-guide/customization/case-item-details.rst
  Showcase/portal-developer-examples/resources/files/variables.Portal.CaseDetails.json
Labels: enhancement

#2252 IVYPORTAL-19306 Fix unstable screenshot test
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/AdditionalComponentsScreenshotTest.java
Labels: enhancement

#2253 IVYPORTAL-19352 Filter button should not trigger automatically when focused
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement, skip-changelog

#2250 IVYPORTAL-19177 Advance UI findings
  AxonIvyPortal/portal/webContent/layouts/BasicTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement, skip-changelog

#2260 Feature/ivyportal 19222 provide a mechanism to turn off the shortcuts document
  Documentation/portal-guide/source/portal-user-guide/accessibility/index.rst
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
  Documentation/portal-guide/source/portal-user-guide/my-profile/index.rst
Labels: enhancement, skip-changelog

#2249 IVYPORTAL-18926 Show business detail directly in case detail (#2200)
  AxonIvyPortal/portal-selenium-test/resources/testFile/custom-case-details.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/AbstractConfigurableContentBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/WidgetType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/widget/AbstractWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/widget/BusinessDetailsWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/CustomWidgetParam.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CustomWidgetUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/UrlUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/BusinessDetailsUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemBusinessDetails/CaseItemBusinessDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemBusinessDetails/CaseItemBusinessDetailsData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemBusinessDetails/CaseItemBusinessDetailsProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/webContent/resources/js/case-details.js
  Documentation/portal-guide/source/portal-developer-guide/customization/case-item-details.rst
  Showcase/portal-developer-examples/resources/files/variables.Portal.CaseDetails.json
  Showcase/portal-user-examples/processes/Business Processes/CreateTestData.p.json
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/CustomWidgetNote/CustomWidgetNoteProcess.p.json
Labels: enhancement

#2264 feature/IVYPORTAL-19222-Provide-mechanism-to-turn-off-the-shortcuts
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/UserSettingService.java
Labels: enhancement, skip-changelog

#2274 feature/IVYPORTAL-19222-Provide-a-mechanism-to-turn-off-the-shortcuts
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
Labels: enhancement, skip-changelog

#2275 IVYPORTAL-19305 Enhance My Profile accessibility
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/UserProfile/UserProfile.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/taskwidget/ActivatorFilterColumn/ActivatorFilterColumn.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/taskwidget/PriorityFilterColumn/PriorityFilterColumn.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/taskwidget/StateFilterColumn/StateFilterColumn.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/NumberFilterColumn/NumberFilterColumn.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/TextFilterColumn/TextFilterColumn.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/TimestampFilterColumn/TimestampFilterColumn.xhtml
Labels: enhancement

#2223 IVYPORTAL-19213 Welcome Widget Image and Home Logo alt text can be configured by user
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetConfigurationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/WelcomeDashboardWidget.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
Labels: enhancement

#2233 IVYPORTAL-19233 Enhance focus and tab key for accessibility
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DateTimePatternBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/DateTimeGlobalSettingService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseDocuments/CaseDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardAddNewWidgets.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardDetailModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CustomWidgetConfiguration/CustomWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/Absence.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/UserProfile/UserProfile.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettings.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemHistory/CaseItemHistory.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ColumnsConfiguration/ColumnsConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemGeneralInfo/TaskItemGeneralInfo.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemWorkflowEvents/TaskItemWorkflowEvents.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/WarningBeforeLeavingTask/WarningBeforeLeavingTask.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/filter/CaseCreationDateFilter/CaseCreationDateFilter.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/filter/CaseFinishedDateFilter/CaseFinishedDateFilter.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/filter/CaseStateFilter/CaseStateFilter.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/CategoryFilterColumn/CategoryFilterColumn.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/TimestampFilterColumn/TimestampFilterColumn.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/statistic/StatisticFilters/StatisticFilters.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/filter/TaskCompletedDateFilter/TaskCompletedDateFilter.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/filter/TaskCreationDateFilter/TaskCreationDateFilter.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/filter/TaskExpiredDateFilter/TaskExpiredDateFilter.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/filter/TaskStateFilter/TaskStateFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/ShareLinkDialog/ShareLinkDialog.xhtml
  AxonIvyPortal/portal/webContent/layouts/decorator/portal-dialog-with-icon.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/AbstractTaskTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#2277 Feature/ivyportal 19222 provide mechanism to turn off the shortcuts 10 document
  Documentation/portal-guide/source/portal-user-guide/accessibility/index.rst
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
  Documentation/portal-guide/source/portal-user-guide/my-profile/index.rst
Labels: enhancement, skip-changelog

#2290 IVYPORTAL-19306 Update documentation reversion 13.2.0-m278
  Documentation/maven/pom.xml
Labels: skip-changelog

#2291 IVYPORTAL-19306 Revert documentation reversion 13.2.0-m278
  Documentation/maven/pom.xml
Labels: skip-changelog

#2292 IVYPORTAL-19418 Convert project
  AxonIvyPortal/PortalKitTestHelper/.classpath
  AxonIvyPortal/PortalKitTestHelper/.gitignore
  AxonIvyPortal/PortalKitTestHelper/.settings/ch.ivyteam.ivy.designer.prefs
  AxonIvyPortal/PortalKitTestHelper/.settings/org.eclipse.wst.common.component
  AxonIvyPortal/portal-components/.classpath
  AxonIvyPortal/portal-components/.gitignore
  AxonIvyPortal/portal-components/.settings/ch.ivyteam.ivy.designer.prefs
  AxonIvyPortal/portal-components/.settings/org.eclipse.wst.common.component
  AxonIvyPortal/portal-selenium-test/.classpath
  AxonIvyPortal/portal-selenium-test/.gitignore
  AxonIvyPortal/portal-selenium-test/.settings/ch.ivyteam.ivy.designer.prefs
  AxonIvyPortal/portal-selenium-test/.settings/org.eclipse.wst.common.component
  AxonIvyPortal/portal/.classpath
  AxonIvyPortal/portal/.gitignore
  AxonIvyPortal/portal/.settings/ch.ivyteam.ivy.designer.prefs
  AxonIvyPortal/portal/.settings/org.eclipse.wst.common.component
  Showcase/InternalSupport/.classpath
  Showcase/InternalSupport/.gitignore
  Showcase/InternalSupport/.settings/ch.ivyteam.ivy.designer.prefs
  Showcase/InternalSupport/.settings/org.eclipse.wst.common.component
  Showcase/portal-components-examples/.classpath
  Showcase/portal-components-examples/.gitignore
  Showcase/portal-components-examples/.settings/ch.ivyteam.ivy.designer.prefs
  Showcase/portal-components-examples/.settings/org.eclipse.wst.common.component
  Showcase/portal-developer-examples/.classpath
  Showcase/portal-developer-examples/.gitignore
  Showcase/portal-developer-examples/.settings/ch.ivyteam.ivy.designer.prefs
  Showcase/portal-developer-examples/.settings/org.eclipse.wst.common.component
  Showcase/portal-user-examples/.classpath
  Showcase/portal-user-examples/.gitignore
  Showcase/portal-user-examples/.settings/ch.ivyteam.ivy.designer.prefs
  Showcase/portal-user-examples/.settings/org.eclipse.wst.common.component
Labels: skip-changelog
