Repository axonivy-market/portal, pull requests merged in 2025-02, with the labels that each got.

#1476 Updated all pom build.plugin.version=, ivy.engine.version=12.0.4, ver…
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1477 Update pom.xml
  AxonIvyPortal/AxonIvyExpress/pom.xml
Labels: skip-changelog

#1478 bug/IVYPORTAL-18401 Added updating config for Express in update-pom build
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1470 IVYPORTAL 18243 Edit external link UI not align
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
Labels: enhancement

#1481 IVYPORTAL 1824 Edit external link UI not align
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
Labels: enhancement

#1484 feature/IVYPORTAL 18271 Improve-UI UX
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
Labels: enhancement

#1488 IVYPORTAL-17180 Enable Process Viewer for a sub case of a business case
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/ProcessViewerUtils.java
Labels: enhancement

#1489 IVYPORTAL-17180 Enable Process Viewer for a sub case of a business case
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/ProcessViewerUtils.java
Labels: enhancement

#1491 IVYPORTAL-17180 Process Viewer does not work in a sub case of a business case v12
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/ProcessViewerTest.java
Labels: skip-changelog

#1492 IVYPORTAL-17180 Process Viewer does not work in a sub case of a business case v13
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/ProcessViewerTest.java
Labels: skip-changelog

#1487 IVYPORTAL-14471 Renaming Standalone UI process starts
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
Labels: enhancement

#1495 feature/IVYPORTAL-18429-Process-image-show-default-image-in-dark-mode-12
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bo/IvyProcess.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/process/DashboardProcess.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/ImageModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessImageMode.xhtml
Labels: enhancement

#1496 Feature/ivyportal 18429 process image show default image in dark mode le
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bo/IvyProcess.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/process/DashboardProcess.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/ImageModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessImageMode.xhtml
Labels: enhancement

#1500 Feature/ivyportal 18429 process image show default image in dark mode le fix test
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bo/ExternalLinkProcessItem.java
Labels: enhancement

#1503 feature/IVYPORTAL-18429-Process-image-show-default-image-in-dark-mode-12-Fix test
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bo/ExternalLinkProcessItem.java
Labels: enhancement

#1498 IVYPORTAL-18374 Enhance the function to show an error message on uploading files
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
  AxonIvyPortal/portal/webContent/resources/js/process-widget.js
Labels: enhancement

#1504 feature/IVYPORTAL-16540-Portal-Delegation-Permission-LE
  Documentation/portal-guide/source/portal-developer-guide/settings/index.rst
Labels: enhancement

#1505 feature/IVYPORTAL-16540-Portal-Delegation-Permission-12
  Documentation/portal-guide/source/portal-developer-guide/settings/index.rst
Labels: enhancement

#1370 Feature/ivyportal 18050 create cache mechanism for dashboard converter to enhance performance ver2
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/LeaveRequestPage.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/IvyCacheIdentifier.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
Labels: enhancement

#1483 IVYPORTAL-17515: Copy Dashboard Widgets with all settings
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardCloneWidgetScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/MainMenuPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCloneWidgetTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/CloneWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/DashboardCloneUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardAddNewWidgets.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/CombinedModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/ImageModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/ProcessWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessGridItem/ProcessGridItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/CloneWidgetDialog/CloneWidgetDialog.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/CloneWidgetDialog/CloneWidgetDialogData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/CloneWidgetDialog/CloneWidgetDialogProcess.p.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/CloneWidgetFromDashboardDialog/CloneWidgetFromDashboardDialog.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/CloneWidgetFromDashboardDialog/CloneWidgetFromDashboardDialogData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/CloneWidgetFromDashboardDialog/CloneWidgetFromDashboardDialogProcess.p.json
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/CardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: enhancement, feature

#1501 IVYPORTAL-17515 Copy Dashboard Widgets with all settings
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: documentation, skip-changelog

#1507 Feature/IVYPORTAL-18368 improve lighthouse accessibility score
  .github/workflows/cron-bot.yml
  .github/workflows/lighthouse-report.yml
  AxonIvyPortal/portal-selenium-test/lighthouse/puppeteer-script.mjs
Labels: enhancement

#1517 Feature/IVYPORTAL-18368 improve lighthouse accessibility score
  .github/workflows/lighthouse-report.yml
  AxonIvyPortal/portal-selenium-test/lighthouse/puppeteer-script.mjs
Labels: enhancement

#1416 feature/IVYPORTAL-18244 Create external link dialog bug
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
Labels: enhancement, skip-changelog

#1518 Feature/ivyportal 18244 create external link dialog bug 12
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
Labels: enhancement

#1512 IVYPORTA 18324 Support bussiness case customfield
  AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/DataCreation.p.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardColumnFormat.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardColumnType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/ExportUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/TaskFilterFieldFactory.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/FieldAdd.xhtml
Labels: enhancement

#1509 IVYPORTAL 18324 support bussiness case customfield
  AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/DataCreation.p.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardColumnFormat.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardColumnType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/ExportUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/TaskFilterFieldFactory.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/FieldAdd.xhtml
Labels: enhancement

#1519 IVYPORTAL-17515 Copy Dashboard Widgets with all settings
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCloneWidgetTest.java
Labels: skip-changelog

#1520 Merge pull request #1519 from axonivy-market/feature/IVYPORTAL-17515-Copy-Dashboard-Widgets-with-all-settings-LE
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCloneWidgetTest.java
Labels: skip-changelog

#1463 IVYPORTAL 18247 Statistic on dark mode enhancement
  AxonIvyPortal/portal/webContent/resources/js/client-statistic.js
Labels: enhancement

#1523 IVYPORTAL-18247 Statistic on dark mode enhancement
  AxonIvyPortal/portal/webContent/resources/js/client-statistic.js
Labels: enhancement

#1485 IVYPORTAL-18408 Make quick global search enabled by default
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/GlobalSearchResultPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/SearchResultPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/globalsearch/GlobalSearchTest.java
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/GlobalSearch/GlobalSearch.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/resources/js/global-search.js
  AxonIvyPortal/portal/webContent/resources/js/portal.js
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1490 IVYPORTAL-18426 Improve resize body function - version LE
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
Labels: enhancement

#1499 IVYPORTAL-17404 Set up SSO azure Entra ID
  Showcase/InternalSupport/resources/sso-master/README.md
  Showcase/InternalSupport/resources/sso-master/compose.yml
  Showcase/InternalSupport/resources/sso-master/ivy.yaml
  Showcase/InternalSupport/resources/sso-master/nginx.conf
Labels: skip-changelog

#1506 feature/IVYPORTAL-18374 Enhance the function to show an error message on uploading files
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
  AxonIvyPortal/portal/webContent/resources/js/process-widget.js
Labels: enhancement

#1527 IVYPORTAL-17515 Copy Dashboard Widgets with all settings
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/CloneWidgetBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/DashboardCloneUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/WelcomeWidgetUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/CloneWidgetDialog/CloneWidgetDialog.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: skip-changelog

#1493 IVYPORTAL-18426 Improve resize body function - version 12
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
Labels: enhancement

#1494 IVYPORTAL-18426 Improve resize body function - version 10
  AxonIvyPortal/portal/webContent/resources/js/dashboard.js
Labels: enhancement

#1528 IVYPORTAL-17515 Copy Dashboard Widgets with all settings
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/CloneWidgetBean.java
Labels: enhancement, skip-changelog

#1508 IVYPORTAL-18440: Introduce variable to skip permission check for Portal 10
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/CaseService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/TaskService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/PermissionUtils.java
Labels: skip-changelog

#1524 IVYPORTAL 18403 Portal custom field display name
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/FieldAdd.xhtml
Labels: enhancement

#1530 IVYPORTAL 18403 Portal custom field display name
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/FieldAdd.xhtml
Labels: enhancement

#1531 IVYPORTAL 18403 Portal custom field display name
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/FieldAdd.xhtml
Labels: enhancement

#1532 feature/IVYPORTAL-18512-release-portal-s271
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCloneWidgetTest.java
Labels: skip-changelog

#1534 Update pom.xml
  Documentation/maven/pom.xml
Labels: skip-changelog

#1538 Merge pull request #1527 from axonivy-market/feature/IVYPORTAL-17515-…
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardCloneWidgetScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCloneWidgetTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/CloneWidgetBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/DashboardCloneUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/WelcomeWidgetUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/CloneWidgetDialog/CloneWidgetDialog.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: skip-changelog

#1427 IVYPORTAL 18266 Multiple highlighting on menu
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardConfiguration/PortalDashboardConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
Labels: enhancement

#1521 IVYPORTAL 18266 Multiple highlighting on menu
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardConfiguration/PortalDashboardConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
Labels: enhancement

#1539 IVYPORTAL-17515 Copy Dashboard Widgets with all settings
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardCloneWidgetScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCloneWidgetTest.java
Labels: skip-changelog

#1516 Feature/ivyportal 18233 create GitHub workflow for screenshot document build le
  .github/workflows/portal-document-screenshot-test.yml
  .github/workflows/portal-documentation.yml
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/FileHelper.java
Labels: enhancement, skip-changelog

#1540 Update portal-document-screenshot-test.yml
  .github/workflows/portal-document-screenshot-test.yml
Labels: skip-changelog

#1497 IVYPORTAL-18417 Show search scope of quick search function
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: enhancement

#1544 Feature/ivyportal 18233 create GitHub workflow for screenshot document build 10
  .github/workflows/portal-document-screenshot-test.yml
  .github/workflows/portal-documentation.yml
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/FileHelper.java
Labels: enhancement, skip-changelog

#1543 Feature/ivyportal 18233 create GitHub workflow for screenshot document build 12
  .github/workflows/portal-document-screenshot-test.yml
  .github/workflows/portal-documentation.yml
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/FileHelper.java
Labels: enhancement, skip-changelog

#1550 IVYPORTAL-17515 Copy Dashboard Widgets with all settings
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
Labels: skip-changelog

#1551 IVYPORTAL-17515 Copy Dashboard Widgets with all settings
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/ImageModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessGridItem/ProcessGridItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
Labels: skip-changelog

#1546 IVYPORTAL-18533-JavaScript-injection-report_10
  AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml
  Documentation/portal-guide/source/portal-developer-guide/components/layout-templates.rst
Labels: enhancement

#1548 IVYPORTAL 18533 JavaScript injection report
  AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml
  Documentation/portal-guide/source/portal-developer-guide/iframe/index.rst
Labels: enhancement

#1547 IVYPORTAL 18533 JavaScript injection report
  AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml
  Documentation/portal-guide/source/portal-developer-guide/iframe/index.rst
Labels: enhancement

#1552 Feature/ivyportal 17515 copy dashboard widgets with all settings le
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/ImageModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessGridItem/ProcessGridItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
Labels: enhancement

#1486 feature/IVYPORTAL-18417-Show-search-scope-of-quick-search-function-12
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: enhancement

#1557 IVYPORTAL-18408 Make quick global search enabled by default
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1525 IVYPORTAL-18408 Make quick global search enabled by default
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/GlobalSearchResultPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/SearchResultPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/globalsearch/GlobalSearchTest.java
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/GlobalSearch/GlobalSearch.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/resources/js/global-search.js
  AxonIvyPortal/portal/webContent/resources/js/portal.js
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1536 IVYPORTAL 18419 Error on Dashboard Case Widget Information
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/CaseSearchCriteria.java
Labels: enhancement

#1522 IVYPORTAL-17212 Portal LTS breadcrumb error
  AxonIvyPortal/portal-components/webContent/resources/js/process-history-component.js
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1549 IVYPORTAL-18398 Case behaviors when click on Case In list
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/Variable.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/GlobalSearchResultPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseBehaviorsTest.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardCaseWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/configuration/GlobalSetting.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/BehaviourWhenClickingOnLineInCaseList.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/UserSettingService.java
  AxonIvyPortal/portal/src/com/axonivy/portal/response/CaseData.java
  AxonIvyPortal/portal/src/com/axonivy/portal/service/GlobalSearchService.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/BusinessDetailsUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/CaseBehaviorUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessCaseWidget/ProcessCaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItem/CaseItemProcess.p.json
Labels: enhancement, feature

#1564 Feature/ivyportal 18398 case widget control click behavior for case details vs business details le
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/Variable.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/GlobalSearchResultPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseBehaviorsTest.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardCaseWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/configuration/GlobalSetting.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/BehaviourWhenClickingOnLineInCaseList.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/UserSettingService.java
  AxonIvyPortal/portal/src/com/axonivy/portal/response/CaseData.java
  AxonIvyPortal/portal/src/com/axonivy/portal/service/GlobalSearchService.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/BusinessDetailsUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/CaseBehaviorUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessCaseWidget/ProcessCaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItem/CaseItemProcess.p.json
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1561 IVYPORTAL-17212 Portal LTS breadcrumb error
  AxonIvyPortal/portal-components/webContent/resources/js/process-history-component.js
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1562 IVYPORTAL-17212 Portal LTS breadcrumb error
  AxonIvyPortal/portal-components/webContent/resources/js/process-history-component.js
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1559 Feature/ivyportal 16167 process widget smart process order by most used
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardProcessWidgetTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/ProcessSorting.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: enhancement, feature

#1565 Feature/ivyportal 16167 process widget smart process order by most used
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardProcessWidgetTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/ProcessSorting.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: enhancement, feature

#1554 Feature/ivyportal 18399 case owners can delegate tasks 12
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/PortalPermission.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/security/PortalSecurity.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CaseUtils.java
Labels: enhancement

#1573 IVYPORTAL-18140 Cleanup css fix guitest
  AxonIvyPortal/portal-selenium-test/resources/testFile/Dashboard_Dashboard_Export.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskEditWidgetNewDashBoardPage.java
Labels: enhancement

#1576 IVYPORTAL-18140 Cleanup css fix guitest (#1573)
  AxonIvyPortal/portal-selenium-test/resources/testFile/Dashboard_Dashboard_Export.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskEditWidgetNewDashBoardPage.java
Labels: enhancement

#1583 Update portal-document-screenshot-test.yml
  .github/workflows/portal-document-screenshot-test.yml
Labels: skip-changelog

#1555 document/IVYPORTAL 18399 Case Owner Can Delegate Tasks
  Documentation/portal-guide/source/portal-developer-guide/permissions/index.rst
  Documentation/portal-guide/source/portal-developer-guide/settings/index.rst
Labels: documentation

#1568 IVYPORTAL-18557: Add paginator template for document table in case details
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
Labels: enhancement

#1567 IVYPORTAL-18557: Add paginator template for document table in case details
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
Labels: enhancement

#1569 IVYPORTAL-18557 Add paginator template for document table in case details
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
Labels: enhancement

#1570 IVYPORTAL 18546 Text overflow not consistently replaced with ellipsis and no consistent tool tips available
  AxonIvyPortal/portal-components/webContent/resources/components/securityMemberNameAndAvatar.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/NameCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/NameCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseCustomField/CaseCustomField.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseDate/CaseDate.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseId/CaseId.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseName/CaseName.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskCustomField/TaskCustomField.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskDate/TaskDate.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskId/TaskId.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskName/TaskName.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskPriority/TaskPriority.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/customization/CaseWidget/CaseWidget.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/customization/TaskWidget/TaskWidget.xhtml
Labels: enhancement

#1584 IVYPORTAL 18546 Text overflow not consistently replaced with ellipsis and no consistent tool tips available (#1570)
  AxonIvyPortal/portal-components/.classpath
  AxonIvyPortal/portal-components/webContent/resources/components/securityMemberNameAndAvatar.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/NameCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/NameCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseCustomField/CaseCustomField.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseDate/CaseDate.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseId/CaseId.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseName/CaseName.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskCustomField/TaskCustomField.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskDate/TaskDate.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskId/TaskId.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskName/TaskName.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskPriority/TaskPriority.xhtml
Labels: enhancement

#1585 IVYPORTAL 18546 Text overflow not consistently replaced with ellipsis and no consistent tool tips available (#1570)
  AxonIvyPortal/portal-components/.classpath
  AxonIvyPortal/portal-components/webContent/resources/components/securityMemberNameAndAvatar.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/NameCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/NameCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseCustomField/CaseCustomField.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseDate/CaseDate.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseId/CaseId.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseName/CaseName.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskCustomField/TaskCustomField.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskDate/TaskDate.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskId/TaskId.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskName/TaskName.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskPriority/TaskPriority.xhtml
Labels: enhancement
