Repository axonivy-market/portal, pull requests merged in 2025-08, with the labels that each got.

#2301 Fix GUI test welcome widget
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
Labels: skip-changelog

#2297 IVYPORTAL-19421 Enhance My Profile accessibility
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessDashboardWidget/ProcessFilter.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/Absence.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/UserProfile/UserProfile.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/TextFilterColumn/TextFilterColumn.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/ApplicationFilter/ApplicationFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/CategoryFilter/CategoryFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/CreatorFilter/CreatorFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/DashboardFilter/DashboardFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/DateFilter/DateFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/IdFilter/IdFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/NumberFilter/NumberFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/PriorityFilter/PriorityFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/ResponsibleFilter/ResponsibleFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/StateFilter/StateFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/TextFilter/TextFilter.xhtml
Labels: enhancement

#2294 IVYPORTAL-19421 Enhance My Profile accessibility
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessDashboardWidget/ProcessFilter.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/Absence.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/UserProfile/UserProfile.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/dashboard/widget/TextFilterColumn/TextFilterColumn.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/ApplicationFilter/ApplicationFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/CategoryFilter/CategoryFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/CreatorFilter/CreatorFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/DashboardFilter/DashboardFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/DateFilter/DateFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/IdFilter/IdFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/NumberFilter/NumberFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/PriorityFilter/PriorityFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/ResponsibleFilter/ResponsibleFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/StateFilter/StateFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/TextFilter/TextFilter.xhtml
Labels: enhancement

#2278 feature/ivyportal 19253 implement static page 12
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/configuration/CustomSubMenuItem.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/MenuKind.java
  AxonIvyPortal/portal-selenium-test/resources/testFile/custom-menu-items.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/MenuTest.java
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuItem.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuNavigator.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/ProcessSubMenuItem.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/SubMenuItem.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageMapper.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/userprofile/homepage/HomepageUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/navigation/PortalNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/UserMenu.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/StaticPageUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/service/CustomSubMenuItemService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/iframe/StaticPageTemplateIFrame/StaticPageTemplateIFrame.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/iframe/StaticPageTemplateIFrame/StaticPageTemplateIFrameData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/iframe/StaticPageTemplateIFrame/StaticPageTemplateIFrameProcess.p.json
  AxonIvyPortal/portal/webContent/layouts/IFramePortalTemplate.xhtml
  Documentation/portal-guide/source/portal-developer-guide/index.rst
  Documentation/portal-guide/source/portal-developer-guide/static-page/index.rst
  Showcase/portal-components-examples/webContent/view/static.xhtml
Labels: enhancement

#2296 IVYPORTAL-19309 Enhance description with tooltip
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CompactDashboardProcessBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/CompactModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/UserProfile/UserProfile.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
Labels: enhancement

#2218 Feature/ivyportal 17444 Condition-based coloring in Portal Statistic Charts
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/StatisticScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CustomStatisticConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/StatisticConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/StatisticWidgetTest.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/StatisticConfigurationBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/ColumnChartConfig.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/PieChartConfig.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/Statistic.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/ThresholdStatisticChart.java
  AxonIvyPortal/portal/src/com/axonivy/portal/enums/statistic/ConditionBasedColoringScope.java
  AxonIvyPortal/portal/src/com/axonivy/portal/enums/statistic/OperatorFieldStatistic.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/StatisticConfiguration/StatisticConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/component/StatisticFilter/StatisticFilter.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/component/ThresholdStatisticChart/ThresholdStatisticChart.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/component/ThresholdStatisticChart/ThresholdStatisticChartData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/component/ThresholdStatisticChart/ThresholdStatisticChartProcess.p.json
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
  AxonIvyPortal/portal/webContent/resources/js/statistic.js
Labels: enhancement, feature

#2312 bug/IVPORTAL-17444-Fix-GUI-test-condition-based-coloring-feature
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/StatisticWidgetTest.java
Labels: skip-changelog

#2318 IVYPORTAL-19253 Implement static page
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/StaticPageUtils.java
  AxonIvyPortal/portal/webContent/layouts/IFramePortalTemplate.xhtml
  Documentation/portal-guide/source/portal-developer-guide/static-page/index.rst
Labels: skip-changelog

#2320 remove continue on error
  .github/workflows/portal-documentation.yml
Labels: skip-changelog

#2322 remove continue on error
  .github/workflows/portal-documentation.yml
Labels: skip-changelog

#2323 Remove cotinue on error
  .github/workflows/portal-documentation.yml
Labels: skip-changelog

#2325 Update index.rst
  Documentation/portal-guide/source/portal-developer-guide-japanese/public-api/index.rst
Labels: skip-changelog

#2326 Feature/ivyportal 19253 implement static page 12
  Documentation/portal-guide/source/portal-developer-guide/static-page/index.rst
Labels: enhancement

#2327 Fix document build job
  Documentation/portal-guide/source/portal-developer-guide-japanese/customization/hide-technical-stuffs.rst
  Documentation/portal-guide/source/portal-developer-guide-japanese/iframe/index.rst
  Documentation/portal-guide/source/portal-developer-guide-japanese/index.rst
  Documentation/portal-guide/source/portal-developer-guide-japanese/installation/index.rst
  Documentation/portal-guide/source/portal-developer-guide-japanese/introduction/index.rst
  Documentation/portal-guide/source/portal-developer-guide-japanese/static-page/index.rst
Labels: skip-changelog

#2305 IVYPORTAL-19422 Enhance focus and "tab" key accessibility
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DateTimePatternBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/DateTimeGlobalSettingService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/CaseInformationInIFrame/CaseInformationInIFrame.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardAddNewWidgets.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/Absence.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemHistory/CaseItemHistory.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemGeneralInfo/TaskItemGeneralInfo.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/ShareLinkDialog/ShareLinkDialog.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/DateFilter/DateFilter.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/AbstractTaskTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/includes/WidgetFilter.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/js/icon-selection.js
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#2341 Update AdditionalComponentsScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/AdditionalComponentsScreenshotTest.java
Labels: skip-changelog

#2351 IVYPORTAL-19447-Handle-feedback-static-pages
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/publicapi/PortalNavigatorAPI.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/StaticPageUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/service/CustomSubMenuItemService.java
  Showcase/portal-components-examples/dataclasses/com/axonivy/portal/components/examples/redirectToStaticPageExampleData.d.json
  Showcase/portal-components-examples/processes/Start Processes/redirectToStaticPageExample.p.json
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/redirectToStaticPageExample/redirectToStaticPageExample.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/redirectToStaticPageExample/redirectToStaticPageExampleData.d.json
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/redirectToStaticPageExample/redirectToStaticPageExampleProcess.p.json
  Showcase/portal-components-examples/webContent/view/static.xhtml
Labels: skip-changelog

#2363 IVYPORTAL-19240 Integrate Portal Documentation into Weblate
  .github/workflows/portal-documentation-weblate.yml
Labels: skip-changelog

#2368 Feature/ivyportal 19447 handle feedback static pages
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/publicapi/PortalNavigatorAPI.java
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
Labels: enhancement

#2376 bug/Portal-Documentation-Screenshot-update-pom-file
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
Labels: skip-changelog

#2377 bug/IVYPORTAL-19529-Portal-Document-Screenshot-build-error-on-GitHub
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
Labels: skip-changelog

#2380 Updated all pom build.plugin.version=, ivy.engine.version=12.0.9, version
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog
