Repository axonivy-market/portal, pull requests merged in 2025-09, with the labels that each got.

#2338 bug/IVYPORTAL-19464-Error-when-updating-absence-in-10
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/AbsenceManagementProcess.p.json
Labels: bug, skip-changelog

#2389 IVYPORTAL-19350 Implement Doc Viewer with sub process and signature s…
  AxonIvyPortal/portal-components/dataclasses/com/axonivy/portal/components/PreviewDocumentData.ivyClass
  AxonIvyPortal/portal-components/processes/Functional Processes/PreviewDocument.p.json
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/DocumentUploadBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/DocumentUtils.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseTaskDocumentBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentData.ivyClass
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsData.ivyClass
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-case-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-task-list/index.rst
Labels: feature

#2384 IVYPORTAL-19523 Task is not destroyed on expiry
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemGeneralInfo/TaskItemGeneralInfoProcess.p.json
Labels: bug

#2386 IVYPORTAL-19088 Display open tasks for case owner
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-has-one-task-widget.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/DashboardTaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/TaskDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/TaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/DashboardTaskService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/TaskService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/DashboardWidgetInformationService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskDashboardWidgetProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidgetConfiguration/TaskWidgetConfiguration.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: enhancement

#2385 IVYPORTAL-19088 Display open tasks for case owner
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-has-one-task-widget.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/DashboardTaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/TaskDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/TaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/DashboardTaskService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/TaskService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/DashboardWidgetInformationService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskDashboardWidgetProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidgetConfiguration/TaskWidgetConfiguration.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: enhancement

#2400 IVYPORTAL-19523 Task is not destroyed on expiry
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemGeneralInfo/TaskItemGeneralInfoProcess.p.json
Labels: bug

#2392 IVYPORTAL-19536 Content spoofing and svg cross site scripting
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/document/DocumentDetectorFactory.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/document/DocumentExtensionConstants.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/document/PDFDocumentDetector.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/document/SVGSecurityScanner.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/document/WordDocumentDetector.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/ImageUploadResult.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetConfigurationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ExternalLinkBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/DocumentDetectorFactory.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/ExcelDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/PDFDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/SVGSecurityScanner.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/WordDocumentDetector.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/ExternalLinkUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/PortalSanitizeUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/UploadDocumentUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/WelcomeWidgetUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/iframe/TaskTemplateIFrame/TaskTemplateIFrameProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/webContent/resources/js/iframe-task-template.js
Labels: bug, enhancement

#2388 IVYPORTAL-18976 Filter system task
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/Variable.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDetailsTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/GlobalSettingService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemHistory/CaseItemHistory.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemHistory/CaseItemHistoryProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemNotes/TaskItemNotes.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemNotes/TaskItemNotesProcess.p.json
  Documentation/portal-guide/source/portal-user-guide-japanese/admin-settings/documents/available_settings.csv
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#2405 IVYPORTAL-19324 Implement Renaming functionality in Document table 12
  AxonIvyPortal/portal-components/cms/cms_de.yaml
  AxonIvyPortal/portal-components/cms/cms_en.yaml
  AxonIvyPortal/portal-components/cms/cms_es.yaml
  AxonIvyPortal/portal-components/cms/cms_fr.yaml
  AxonIvyPortal/portal-components/cms/cms_ja.yaml
  AxonIvyPortal/portal-components/dataclasses/com/axonivy/portal/components/RenameDocumentItemData.d.json
  AxonIvyPortal/portal-components/processes/Functional Processes/RenameDocumentItem.p.json
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentUtilsBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/constant/PortalComponentConstants.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/converter/FilenameConverter.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/CustomSignature.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/NewFilenameValidation.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/service/CaseDocumentService.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableData.d.json
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalCasesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/RenameDocumentTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseDocuments/CaseDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseDocuments/CaseDocumentsData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseDocuments/CaseDocumentsProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocumentsData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocumentsProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json
  AxonIvyPortal/portal/webContent/resources/css/module.css
  Documentation/portal-guide/source/portal-components/document-table/index.rst
  Documentation/portal-guide/source/portal-components/documents/document_table_component_attributes.csv
  Documentation/portal-guide/source/portal-user-guide/full-case-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-task-list/index.rst
  Showcase/portal-components-examples/dataclasses/com/axonivy/portal/components/examples/CustomDocumentFeaturesData.d.json
  Showcase/portal-components-examples/processes/Functional Processes/CustomDocumentFeatures.p.json
Labels: enhancement, feature

#2416 Revert "IVYPORTAL-19350 Implement Doc Viewer with sub process and sig…
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/DocumentUtils.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseTaskDocumentBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-case-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-task-list/index.rst
Labels: skip-changelog

#2409 IVYPORTAL-19324 Implement Renaming functionality in Document table
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/converter/FilenameConverter.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/RenameDocumentTest.java
  AxonIvyPortal/portal/dataclasses/portalkit/RenameDocumentData.ivyClass
  AxonIvyPortal/portal/processes/Functional Processes/RenameDocument.p.json
  AxonIvyPortal/portal/src/com/axonivy/portal/enums/PortalCustomSignature.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseDocuments/CaseDocumentsProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocumentsProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json
  Documentation/portal-guide/source/portal-components/document-table/index.rst
  Showcase/portal-components-examples/processes/Functional Processes/CustomDocumentFeatures.p.json
Labels: skip-changelog

#2382 IVYPORTAL-19031 Support open main menu item in new tab
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuItem.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
  AxonIvyPortal/portal/webContent/resources/js/application-selection-menu.js
Labels: enhancement

#2422 IVYPORTAL-19593 Disable Jenkins Selenium Test MASTER
  build/gui-test-new-dashboard/Jenkinsfile
Labels: skip-changelog

#2394 feature/IVYPORTAL-19350-Implement-Doc-Viewer-with-sub-process-and-signature-search-mechanism-13
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/DocumentUploadBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/DocumentUtils.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseTaskDocumentBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-case-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-task-list/index.rst
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/DocumentTableExample/DocumentTableExample.xhtml
Labels: enhancement, feature

#2426 IVYPORTAL-19594 Stabilize test for release
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/MainMenuPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/SystemNoteVisibilityTest.java
Labels: skip-changelog

#2427 IVYPORTAL-19088 Check filter system task by permission (#2425)
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/DashboardTaskService.java
Labels: skip-changelog

#2432 Updated all pom build.plugin.version=, ivy.engine.version=, version=12.0.10-SNAPSHOT
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-product/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Documentation/public-api/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-demo-app/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#2433 Bug/improve failed tests in master
  AxonIvyPortal/portal/webContent/resources/js/iframe-task-template.js
Labels: skip-changelog

#2402 IVYPORTAL-19442 Collapsed menu not readable by screen reader in task
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
  AxonIvyPortal/portal/webContent/resources/js/application-selection-menu.js
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: bug

#2401 IVYPORTAL-19442 Collapsed menu not readable by screen reader in task
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: bug

#2448 IVYPORTAL-19604 Stabilize Selenium tests
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/MainMenuPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NoteHistoryPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EnhanceVisibilityTasksForMemberOfRoleTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/SystemNoteVisibilityTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
Labels: enhancement, skip-changelog

#2445 IVYPORTAL-19201 Update datatable after sorting
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
Labels: enhancement

#2453 IVYPORTAL-19324 Menu dashboard title does not have multi language
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
Labels: skip-changelog

#2421 IVYPORTAL-19324 Implement Renaming functionality in Document table LE
  AxonIvyPortal/portal-components/cms/cms_de.yaml
  AxonIvyPortal/portal-components/cms/cms_en.yaml
  AxonIvyPortal/portal-components/cms/cms_es.yaml
  AxonIvyPortal/portal-components/cms/cms_fr.yaml
  AxonIvyPortal/portal-components/cms/cms_ja.yaml
  AxonIvyPortal/portal-components/dataclasses/com/axonivy/portal/components/RenameDocumentItemData.d.json
  AxonIvyPortal/portal-components/processes/Functional Processes/RenameDocumentItem.p.json
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentUtilsBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/constant/PortalComponentConstants.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/converter/FilenameConverter.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/CustomSignature.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/NewFilenameValidation.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/service/CaseDocumentService.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableData.d.json
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/PortalCasesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/RenameDocumentTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseDocuments/CaseDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseDocuments/CaseDocumentsData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/CaseDocuments/CaseDocumentsProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocumentsData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocumentsProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json
  AxonIvyPortal/portal/webContent/resources/css/module.css
  Documentation/portal-guide/source/portal-components/document-table/index.rst
  Documentation/portal-guide/source/portal-components/documents/document_table_component_attributes.csv
  Documentation/portal-guide/source/portal-user-guide/full-case-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-task-list/index.rst
  Showcase/portal-components-examples/dataclasses/com/axonivy/portal/components/examples/CustomDocumentFeaturesData.d.json
  Showcase/portal-components-examples/processes/Functional Processes/CustomDocumentFeatures.p.json
Labels: feature

#2367 IVYPORTAL-19481 Error when preview on task/case configuration widget
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidgetConfiguration/CaseWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidgetConfiguration/TaskWidgetConfiguration.xhtml
Labels: bug

#2415 IVYPORTAL-19562 Add logo alt text configuration
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
Labels: enhancement

#2459 IVYPORTAL-19562 Add logo alt text configuration - handle feedback
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
Labels: skip-changelog

#2469 Update pom.xml to 10.0.31
  Documentation/maven/pom.xml
Labels: skip-changelog

#2464 IVYPORTAL-19590 Improve accessibility
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/CombinedModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/ImageModeProcess.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessImageMode.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessGridItem/ProcessGridItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/js/application-selection-menu.js
Labels: enhancement

#2471 Update pom.xml to 10.0.32-SNAPSHOT
  Documentation/maven/pom.xml
Labels: skip-changelog

#2447 IVYPORTAL-19348 Update document table component to use UUID
  AxonIvyPortal/portal-components/processes/Functional Processes/GetDocumentItems.p.json
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal/processes/Functional Processes/GetDocumentList.p.json
  Documentation/portal-guide/source/portal-components/document-table/index.rst
  Showcase/portal-components-examples/processes/Functional Processes/CustomDocumentFeatures.p.json
  build/gui-test-new-dashboard/Jenkinsfile
Labels: enhancement

#2479 Feature/ivyportal 19348 updating document table component to use UUID v le
  build/gui-test-new-dashboard/Jenkinsfile
Labels: enhancement, skip-changelog

#2481 IVYPORTAL-19348 Updating document table component to use UUID
  AxonIvyPortal/portal-components/processes/Functional Processes/GetDocumentItems.p.json
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal/processes/Functional Processes/GetDocumentList.p.json
  Documentation/portal-guide/source/portal-components/document-table/index.rst
  Showcase/portal-components-examples/processes/Functional Processes/CustomDocumentFeatures.p.json
Labels: bug

#2475 IVYPORTAL-19542 Correct German wording for "Share" label
  AxonIvyPortal/portal/cms/cms_de.yaml
Labels: skip-changelog

#2473 IVYPORTAL-19604 Stabilize Selenium tests LTS12
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EscalationTaskTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetActionTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java
Labels: skip-changelog

#2484 IVYPORTAL-19604 Stabilize Selenium tests
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EscalationTaskTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetActionTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskTemplateIFrameTest.java
Labels: enhancement, skip-changelog

#2485 IVYPORTAL-19604 Stabilize Selenium tests LTS12
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java
Labels: skip-changelog

#2486 IVYPORTAL-19604 Stabilize Selenium tests
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java
Labels: skip-changelog

#2458 Feature/ivyportal 19446 switch to engine translation service le
  AxonIvyPortal/PortalKitTestHelper/dataclasses/portalKit_test/IvyVariableHelperData.d.json
  AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/IvyVariableHelper.p.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/Variable.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/MultiLanguageTranslationSupportScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/WidgetSupportMultiLanguageTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardNewsWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardSupportMultiLanguageTest.java
  AxonIvyPortal/portal/.classpath
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/rest-clients.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/dataclasses/com/axonivy/portal/data/functional/DeepLData.d.json
  AxonIvyPortal/portal/lib/generated/rest/jaxRsClient_4a403c04-f107-44f0-9eb8-92f9c27f7ed1.jar
  AxonIvyPortal/portal/processes/Functional Processes/DeepL.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/IMultiLanguage.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ExternalLinkBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ThirdPartyApplicationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/com/axonivy/connector/deepl/DeepLAuthFeature.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/NewsWidgetBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/service/DeepLTranslationService.java
  AxonIvyPortal/portal/src/com/axonivy/portal/service/IvyTranslationService.java
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
  Documentation/portal-guide/source/portal-user-guide-japanese/admin-settings/documents/available_settings.csv
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
  Documentation/portal-guide/source/portal-user-guide/portal-multi-language/index.rst
Labels: enhancement

#2467 IVYPORTAL-19589 Duplicate key error when adding custom fields in task widget
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/DashboardWidgetExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/AbstractTaskWidgetFilterBean.java
Labels: bug

#2510 IVYPORTAL-19632 Improve documentation
  Documentation/portal-guide/source/portal-developer-guide/permissions/index.rst
Labels: enhancement, skip-changelog

#2517 IVYPORTAL-19632 Improve documentation
  Documentation/portal-guide/source/portal-developer-guide/permissions/index.rst
Labels: skip-changelog

#2516 Feature/ivyportal 19632 improve destroy task documentation 10.1
  Documentation/portal-guide/source/portal-developer-guide/permissions/index.rst
Labels: skip-changelog

#2515 IVYPORTAL-19632 Improve documentation
  Documentation/portal-guide/source/portal-developer-guide/permissions/index.rst
Labels: enhancement, skip-changelog

#2505 IVYPORTAL-19589 Duplicate key error when adding custom fields in task widget
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/DashboardWidgetExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/AbstractTaskWidgetFilterBean.java
Labels: bug

#2524 bug/IVYPORTAL-19589-Duplicate-column-error-when-adding-in-task-widget
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
Labels: skip-changelog

#2450 IVYPORTAL-19604 Stabilize Selenium tests
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseEditWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardModificationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/GlobalSearchResultPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/MainMenuPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NoteHistoryPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskIFrameTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EnhanceVisibilityTasksForMemberOfRoleTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EscalationTaskTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/ShowCaseNoteHistoryTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/SystemNoteVisibilityTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseBehaviorsTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCaseWidgetFilterTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetActionTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/CustomTaskDelegateTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDetailsTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskTemplateIFrameTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/PortalPermission.java
Labels: enhancement, skip-changelog

#2532 IVYPORTAL-19604 Enable Selenium build on Jenkins
  build/gui-test-new-dashboard/Jenkinsfile
Labels: enhancement

#2414 IVYPORTAL-19408 Dashboard Widget Table Header Not Algin Correctly
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: bug

#2523 IVYPORTAL-19633 Cannot rename document after preview
  AxonIvyPortal/portal-components/cms/cms.yaml
  AxonIvyPortal/portal-components/cms/cms_de.yaml
  AxonIvyPortal/portal-components/cms/cms_en.yaml
  AxonIvyPortal/portal-components/cms/cms_es.yaml
  AxonIvyPortal/portal-components/cms/cms_fr.yaml
  AxonIvyPortal/portal-components/cms/cms_ja.yaml
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/DocumentUtils.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocumentProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json
Labels: bug

#2548 IVYPORTAL-19604 Stabilize DocumentTableComponentTest
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/component/DocumentTableComponentPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/DocumentTableComponentTest.java
Labels: enhancement, skip-changelog

#2554 IVYPORTAL-19671 Improve not so good screenshots
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AbsencePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/StatisticConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
Labels: enhancement, skip-changelog
