Repository axonivy-market/portal, pull requests merged in 2025-04, with the labels that each got.

#1719 IVYPORTAL-18814 Fix unstable testcases LTS 10
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AdminSettingsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
Labels: enhancement, skip-changelog

#1691 IVYPORTAL-18610: Analyze and add timeout to Portal caches if needed
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/constant/IvyCacheIdentifier.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/PortalVariable.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/service/IvyCacheService.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/IvyCacheIdentifier.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/PortalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/IvyCacheService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettingsProcess.p.json
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1717 IVYPORTAL-18601 Add value for alt attribute in welcome widget LE
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
Labels: enhancement

#1718 IVYPORTAL-18601 Add value for alt attribute in welcome widget 12
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
Labels: enhancement

#1713 IVYPORTAL-18601 Add value for alt attribute in welcome widget 10
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
Labels: enhancement

#1714 IVYPORTAL-18692 Navigation dashboard widget
  AxonIvyPortal/portal-selenium-test/jmeter/configuration/variables.Portal.Dashboard.json
  AxonIvyPortal/portal-selenium-test/resources/testFile/complex-dashboard.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardModificationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NavigationDashboardWidgetConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NavigationDashboardWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/MenuTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/StickyNavigationDashboardTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardNavigationWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardRestoreConfigurationTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuItem.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/NavigationDashboardWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/Dashboard.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/DashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardDisplayType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardWidgetType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/DashboardImportBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/dto/dashboard/NavigationDashboardWidget.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboard/converter/JsonDashboardConverterFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboard/converter/v131/DashboardConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboardtemplate/converter/v131/DashboardTemplateConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/DashboardCloneUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardAddNewWidgets.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardDetailModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidgetData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidgetProcess.p.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfigurationData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfigurationProcess.p.json
  AxonIvyPortal/portal/webContent/layouts/BasicTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: enhancement, feature

#1723 IVYPORTAL-18692: Navigation Dashboard Widget
  Documentation/portal-guide/source/portal-developer-guide/dashboard/index.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-navigation-dashboard-widget.rst
  Documentation/portal-guide/source/portal-user-guide/dashboard-configuration/index.rst
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: skip-changelog

#1722 IVYPORTAL-18610: Analyze and add timeout to Portal caches if needed
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/constant/IvyCacheIdentifier.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/PortalVariable.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/service/IvyCacheService.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/IvyCacheIdentifier.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/PortalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/IvyCacheService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettingsProcess.p.json
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1729 IVYPORTAL-18545 Columns get hidden automatically when using the case details
  AxonIvyPortal/portal-components/cms/cms_de.yaml
  AxonIvyPortal/portal-components/cms/cms_en.yaml
  AxonIvyPortal/portal-components/cms/cms_es.yaml
  AxonIvyPortal/portal-components/cms/cms_fr.yaml
  AxonIvyPortal/portal-components/cms/cms_ja.yaml
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/GlobalVariable.java
  AxonIvyPortal/portal-components/webContent/resources/components/securityMemberNameAndAvatar.xhtml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
  Documentation/portal-guide/source/portal-components/documents/security_member_name_and_avatar_component_attributes.csv
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1730 IVYPORTAL-18545 Columns get hidden automatically when using the case details
  AxonIvyPortal/portal-components/cms/cms_de.yaml
  AxonIvyPortal/portal-components/cms/cms_en.yaml
  AxonIvyPortal/portal-components/cms/cms_es.yaml
  AxonIvyPortal/portal-components/cms/cms_fr.yaml
  AxonIvyPortal/portal-components/cms/cms_ja.yaml
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/GlobalVariable.java
  AxonIvyPortal/portal-components/webContent/resources/components/securityMemberNameAndAvatar.xhtml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
  Documentation/portal-guide/source/portal-components/documents/security_member_name_and_avatar_component_attributes.csv
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1731 Revert "IVYPORTAL-18692 Navigation dashboard widget"
  AxonIvyPortal/portal-selenium-test/jmeter/configuration/variables.Portal.Dashboard.json
  AxonIvyPortal/portal-selenium-test/resources/testFile/complex-dashboard.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardModificationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NavigationDashboardWidgetConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NavigationDashboardWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/MenuTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/StickyNavigationDashboardTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardNavigationWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardRestoreConfigurationTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuItem.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/NavigationDashboardWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/Dashboard.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/DashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardDisplayType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardWidgetType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/DashboardImportBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/dto/dashboard/NavigationDashboardWidget.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboard/converter/JsonDashboardConverterFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboard/converter/v131/DashboardConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboardtemplate/converter/v131/DashboardTemplateConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/DashboardCloneUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardAddNewWidgets.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardDetailModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidgetData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidgetProcess.p.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfigurationData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfigurationProcess.p.json
  AxonIvyPortal/portal/webContent/layouts/BasicTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: enhancement, skip-changelog

#1733 Feature/ivyportal 18888 update integration build 10
  build/integration/Jenkinsfile
Labels: skip-changelog

#1734 Handle UI feedback
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/SelectDeputy.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
Labels: skip-changelog

#1735 feature/IVYPORTAL-18833-Handle-new-feedback-from-Ricoh-for-Portal-Japanese-LE
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/SelectDeputy.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
Labels: skip-changelog

#1738 IVYPORTAL-18716 Update documentation reversion
  Documentation/maven/pom.xml
Labels: enhancement

#1739 IVYPORTAL-18716 Revert documentation reversion
  Documentation/maven/pom.xml
Labels: enhancement

#1736 Feature/ivyportal 18888 update integration build (#1733)
  build/integration/Jenkinsfile
Labels: skip-changelog

#1737 IVYPORTAL-18888 Fix integration failed build
  build/integration/Jenkinsfile
Labels: skip-changelog

#1744 IVYPORTAL-18902 Create release 12.0.5
  Documentation/maven/pom.xml
Labels: skip-changelog

#1746 IVYPORTAL-18902 Create release 12.0.5
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-product/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Documentation/public-api/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-demo-app/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1747 IVYPORTAL-18904-Fix-GUI-test
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java
Labels: skip-changelog

#1748 IVYPORTAL-18904-Fix-GUI-test
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EnhanceVisibilityTasksForMemberOfRoleTest.java
Labels: skip-changelog

#1749 IVYPORTAL-18904-Fix-GUI-test
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java
Labels: skip-changelog

#1751 Update revision
  Documentation/maven/pom.xml
Labels: skip-changelog

#1752 Revert "Update revision"
  Documentation/maven/pom.xml
Labels: skip-changelog

#1766 Updated all pom build.plugin.version=, ivy.engine.version=10.0.28, ve…
  AxonIvyPortal/AxonIvyExpress/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1657 Feature/ivyportal 18574 aggregation for custom statistic chart configuration
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/StatisticConfigurationBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/Statistic.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/StatisticAggregation.java
  AxonIvyPortal/portal/src/com/axonivy/portal/enums/statistic/AdditionalChartConfig.java
  AxonIvyPortal/portal/src/com/axonivy/portal/enums/statistic/AggregationField.java
  AxonIvyPortal/portal/src/com/axonivy/portal/enums/statistic/AggregationInterval.java
  AxonIvyPortal/portal/src/com/axonivy/portal/enums/statistic/ChartTarget.java
  AxonIvyPortal/portal/src/com/axonivy/portal/enums/statistic/ChartType.java
  AxonIvyPortal/portal/src/com/axonivy/portal/service/StatisticService.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/StatisticConfiguration/StatisticConfiguration.xhtml
  AxonIvyPortal/portal/webContent/resources/js/statistic.js
  build/ci/Jenkinsfile
Labels: enhancement

#1771 Feature/ivyportal 18795 Show more information destroy and reset dialog
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskWidgetBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/ActionsCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/ActionsCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItem/CaseItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/TaskAction.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskAction.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/SearchResultsTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
Labels: enhancement
