Repository axonivy-market/portal, pull requests merged in 2025-05, with the labels that each got.

#1741 IVYPORTAL-18555 Case category filter doesn't respect CaseReadAll permission
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CaseTreeUtils.java
Labels: enhancement

#1776 Feature/ivyportal 18795 Show more information destroy dialog
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskWidgetBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/ActionsCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/ActionsCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItem/CaseItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/TaskAction.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskAction.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/SearchResultsTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
Labels: enhancement

#1782 Feature/ivyportal 18795 Show more information in destroy dialog
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskWidgetBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseDashboardWidget/CaseDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/ActionsCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/ActionsCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItem/CaseItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/TaskAction.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskAction.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItem/TaskItem.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/SearchResultsTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
Labels: enhancement

#1786 feature/IVYPORTAL-18795-Show-more-information-Destroy-Update-CMS
  AxonIvyPortal/portal/cms/cms_es.yaml
Labels: enhancement, skip-changelog

#1788 feature/IVYPORTAL-18795-Show-more-information-Fix
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskWidgetBean.java
Labels: enhancement, skip-changelog

#1796 Update revision after create sprint release
  Documentation/maven/pom.xml
Labels: skip-changelog

#1798 Implement
  AxonIvyPortal/PortalKitTestHelper/src/ch/ivy/addon/portalkit/test/util/SecurityUtils.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/chat/ChatGroupUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/PermissionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/internal/RelatedTaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CaseUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/DashboardCloneUtils.java
Labels: skip-changelog

#1800 Feature/ivyportal 18946 integrate portal cms into weblate
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
Labels: enhancement

#1767 Document/ivyportal 18830 implement navigation widget
  Documentation/portal-guide/source/portal-developer-guide/dashboard/index.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-navigation-dashboard-widget.rst
  Documentation/portal-guide/source/portal-user-guide/dashboard-configuration/index.rst
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: skip-changelog

#1743 Feature/ivyportal 18830 Implement Navigation Dashboard Widget
  AxonIvyPortal/portal-selenium-test/jmeter/configuration/variables.Portal.Dashboard.json
  AxonIvyPortal/portal-selenium-test/resources/testFile/complex-dashboard.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardModificationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NavigationDashboardWidgetConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NavigationDashboardWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardDetailsEditPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/MenuTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/StickyNavigationDashboardTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardConfigurationTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardNavigationWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardRestoreConfigurationTest.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuItem.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/NavigationDashboardWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/Dashboard.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/DashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardDisplayType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardWidgetType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/SessionAttribute.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/DashboardImportBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/dto/dashboard/NavigationDashboardWidget.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboard/converter/JsonDashboardConverterFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboard/converter/v131/DashboardConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboardtemplate/converter/v131/DashboardTemplateConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/DashboardCloneUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenu.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardAddNewWidgets.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardDetailModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidgetData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidgetProcess.p.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfigurationData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfigurationProcess.p.json
  AxonIvyPortal/portal/webContent/layouts/BasicTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: enhancement

#1808 Revert "Merge pull request #1707 from axonivy-market/renovate/master-…
  Showcase/InternalSupport/resources/postgres/docker-compose.yml
Labels: skip-changelog

#1813 Potential fix for code scanning alert no. 45: Workflow does not contain permissions
  .github/workflows/cron-bot.yml
Labels: skip-changelog

#1787 Feature/ivyportal 18901 add standard field completed on for task widget
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskWidgetTest.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/CompletedDateColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardStandardTaskColumn.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardProcessTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/dto/dashboard/filter/DashboardFilter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/TaskFilterFieldFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldFinishedDate.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/finisheddate/FinishedDateAfterOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/finisheddate/FinishedDateBeforeOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/finisheddate/FinishedDateBetweenOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/finisheddate/FinishedDateCurrentPeriodOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/finisheddate/FinishedDateEmptyOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/finisheddate/FinishedDateIsOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/finisheddate/FinishedDateNumberOfPeriodsOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/finisheddate/FinishedDateTodayOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/finisheddate/FinishedDateYesterdayOperatorHandler.java
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
Labels: enhancement

#1844 feature/IVYPORTAL-18575-Adapt-multiple-task-activators-in-Portal-12-F…
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldResponsible.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/responsible/ReponsibleContainsOperatorHandler.java
  AxonIvyPortal/portal/webContent/resources/css/module.css
Labels: enhancement

#1845 feature/IVYPORTAL-18575-Adapt-multiple-task-activators-in-Portal-10-F…
  AxonIvyPortal/portal/webContent/resources/css/module.css
Labels: enhancement

#1846 convert process
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidgetProcess.p.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidgetConfiguration/NavigationDashboardWidgetConfigurationProcess.p.json
Labels: enhancement, skip-changelog

#1797 IVYPORTAL-18967: Setting Portal.CaseDetails.ShowDurationTime doesn't …
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemGeneralInformation/CaseItemGeneralInformation.xhtml
Labels: bug

#1780 bug/IVYPORTAL-18942-Positioning-of-button-in-German-for-adding-a-substitute
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/SelectDeputy.xhtml
Labels: skip-changelog

#1851 bug/IVYPORTAL-18942-Positioning-of-button-in-German-for-adding-a-substitute-LE
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/SelectDeputy.xhtml
Labels: skip-changelog

#1781 Feature/ivyportal 18929 Portal page title update
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement, skip-changelog

#1789 IVYPORTAL-18910 Cannot remove filter category of task widget and case widget
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardFilterWidgetTest.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/CaseWidgetUserFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/TaskWidgetUserFilterBean.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/CategoryFilter/CategoryFilter.xhtml
Labels: bug

#1854 feature/IVYPORTAL-18929-Portal-page-title-update
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement, skip-changelog

#1855 IVYPORTAL-18007 Update performance test so that responses are as expected
  AxonIvyPortal/portal-selenium-test/jmeter/portal_walkthrough_testplan.jmx
Labels: enhancement, skip-changelog

#1856 IVYPORTAL-18007 Update performance test so that responses are as expected
  AxonIvyPortal/portal-selenium-test/jmeter/portal_walkthrough_testplan.jmx
Labels: enhancement, skip-changelog

#1769 IVYPORTAL-18575 Adapt multiple task activators in Portal
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/dto/SecurityMemberDTO.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/SecurityMemberDisplayNameUtils.java
  AxonIvyPortal/portal-components/webContent/resources/components/avatar.xhtml
  AxonIvyPortal/portal-components/webContent/resources/components/securityMemberNameAndAvatar.xhtml
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDetailsTest.java
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ResponsibleBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/SecurityMemberDisplayNameFormatBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/PortalConstants.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/ResponsibleColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/TaskService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/SecurityMemberDisplayNameUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/TaskUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/ExpiryRepsonsibleBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/TaskFilterFieldResponsible.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/responsible/ReponsibleContainsOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/responsible/ReponsibleCurrentUserOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/responsible/ResponsibleInOperatorHandler.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskDocuments/TaskDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskNoteHistory/TaskNoteHistory.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/ResponsibleCell.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SecurityMemberDisplayName/SecurityMemberDisplayName.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskExpiryActivatorSelection/TaskExpiryActivatorSelectionProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDelegate/TaskItemDelegateProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemGeneralInfo/TaskItemGeneralInfo.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemGeneralInfo/TaskItemGeneralInfoProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskResponsible/TaskResponsible.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/ExpiryResponsible/ExpiryResponsible.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/ExpiryResponsible/ExpiryResponsibleData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/ExpiryResponsible/ExpiryResponsibleProcess.p.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/Responsibles/Responsibles.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/Responsibles/ResponsiblesData.d.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/Responsibles/ResponsiblesProcess.p.json
  AxonIvyPortal/portal/webContent/layouts/SearchResultsTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  Showcase/InternalSupport/processes/Business Processes/testProcesses/TestTaskFlow.p.json
Labels: enhancement

#1864 bug/IVYPORTAL-18905-Case-widget-Hide-case-creator-update-LE
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CreatorColumnModel.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ColumnManagement/ColumnManagement.xhtml
  AxonIvyPortal/portal/webContent/resources/css/portal.css
Labels: skip-changelog

#1867 bug/IVYPORTAL-18905-Case-widget-Hide-case-creator
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
Labels: skip-changelog

#1866 bug/IVYPORTAL-18905-Case-widget-Hide-case-creator-update
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
Labels: skip-changelog

#1870 feature/IVYPORTAL-18929-Page-title-logic-le
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/LoginBean.java
Labels: enhancement, skip-changelog

#1768 IVYPORTAL-18829 Implementation of pin your task case 12
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/Variable.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskWidgetTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ColumnManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserProfileBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/VisibilityBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/UserProperty.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/DashboardCaseLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/DashboardTaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/CaseDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/DashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/TaskDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CaseColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/PinColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/PinColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardStandardCaseColumn.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardStandardTaskColumn.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DashboardWidgetType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardCaseSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/GlobalSettingService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CaseUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/TaskUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseWidget/CaseWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/UserProfile/UserProfile.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ActionStep/ActionStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/SideStep/SideStep.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CasePin/CasePin.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CasePin/CasePinData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CasePin/CasePinProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskPin/TaskPin.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskPin/TaskPinData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskPin/TaskPinProcess.p.json
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/SidebarWidgetConfiguration.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
  Documentation/portal-guide/source/portal-user-guide/full-case-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/full-task-list/index.rst
  Documentation/portal-guide/source/portal-user-guide/my-profile/index.rst
Labels: enhancement

#1863 IVYPORTAL-18828 Add Expand Button to File Preview
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1772 Feature/ivyportal 18715 statistic migration for customized statistics json le
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables/Portal/Statistic.json
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/StatisticConfigurationBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/ColumnChartConfig.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/Statistic.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/jsonversion/StatisticJsonVersion.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/statistic/converter/JsonStatisticConverterFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/statistic/converter/v131/ClientStatisticConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/statistic/migrator/JsonStatisticMigrator.java
  AxonIvyPortal/portal/src/com/axonivy/portal/service/StatisticService.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/StatisticConfiguration/StatisticConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/component/StatisticFilter/StatisticFilter.xhtml
Labels: enhancement

#1785 IVYPORTAL-18555 Case category filter doesn't respect CaseReadAll permission
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CaseTreeUtils.java
Labels: bug

#1784 IVYPORTAL-18555 Case category filter doesn't respect CaseReadAll permission
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CaseTreeUtils.java
Labels: bug

#1881 IVYPORTAL-19010 Correct Spelling Error in CMS Note
  AxonIvyPortal/portal/cms/cms_de.yaml
Labels: skip-changelog

#1882 IVYPORTAL-18963 - Fix gui test
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskDetailsPage.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/SecurityMemberDisplayNameUtils.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/Responsibles/Responsibles.xhtml
Labels: enhancement

#1883 IVYPORTAL-19010 Correct Spelling Error in CMS Note
  AxonIvyPortal/portal/cms/cms_de.yaml
Labels: skip-changelog

#1884 IVYPORTAL-19010 Correct Spelling Error in CMS Note
  AxonIvyPortal/portal/cms/cms_de.yaml
Labels: skip-changelog

#1889 Update DashboardTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
Labels: skip-changelog

#1880 IVYPORTAL-18828 Add Expand Button to File Preview
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1879 IVYPORTAL-18828 Add Expand Button to File Preview
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1876 IVYPORTAL-18828 Add Expand Button to File Preview
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocumentsProcess.p.json
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1894 IVYPORTAL-18829 Implementation of pin your task case 12
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CasePin/CasePin.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskPin/TaskPin.xhtml
Labels: enhancement

#1750 IVYPORTAL-18654: Fix accessibility problem related to icon selection
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/IconSelection/IconSelection.xhtml
Labels: skip-changelog

#1895 IVYPORTAL-18654: Fix accessibility problem related to icon select
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/IconSelection/IconSelection.xhtml
Labels: skip-changelog

#1896 IVYPORTAL-18840 Portal 13.1 Quality Pass
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/PortalExceptionBean.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/CanWorkOnFilter/CanWorkOnFilterProcess.p.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/StatisticConfiguration/StatisticConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/StatisticConfiguration/StatisticConfigurationProcess.p.json
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/component/StatisticFilter/StatisticFilterProcess.p.json
Labels: skip-changelog

#1899 IVYPORTAL-19012 Use errorPage bean to check condition to show error details
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/PortalExceptionBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/error/ErrorPage/ErrorPage.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ExceptionDialog/ExceptionDialog.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/GlobalAjaxStatus/GlobalAjaxStatus.xhtml
Labels: enhancement

#1903 bug/IVYPORTAL-19011-DashboardDisplayType-not-correct-when-recreating-default-Task/Case-list
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboard/converter/v131/DashboardConverter.java
Labels: skip-changelog

#1900 IVYPORTAL-18840 Portal 13.1 Quality Pass
  AxonIvyPortal/portal/config/variables.yaml
Labels: skip-changelog

#1905 Update TaskWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskWidgetTest.java
Labels: skip-changelog

#1904 IVYPORTAL-18829 Implementation of pin your task case 12
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/Variable.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskWidgetTest.java
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/constant/UserProperty.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/GlobalSettingService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CaseUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/TaskUtils.java
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1891 IVYPORTAL-19000 Update aria-label for button
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/CombinedModeProcess.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/CardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: enhancement

#1893 IVYPORTAL-19000 Update aria-label for button
  AxonIvyPortal/portal/cms/cms.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessWidget/CombinedModeProcess.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/CardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: enhancement

#1908 IVYPORTAL-18840 Portal 13.1 Quality Pass
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
Labels: skip-changelog

#1647 IVYPORTAL-18646 UI broken category selection dialog 12
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: enhancement

#1646 IVYPORTAL-18646 UI broken category selection dialog
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
Labels: enhancement, skip-changelog

#1910 IVYPORTAL-18923 Improve document for custom styles
  Documentation/portal-guide/source/portal-developer-guide/customization/portal-style-customization-logos-colors-date-patterns.rst
Labels: documentation

#1901 IVYPORTAL-18997 Issue with reset filters button in complex filter
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: enhancement, skip-changelog

#1913 feature/ivyportal-18901-add-standard-field-completed-on-for-task-widget
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
Labels: skip-changelog

#1914 Feature/ivyportal 18901 add standard field completed on for task widget 12
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/exporter/TaskDashboardExporter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
Labels: skip-changelog

#1916 IVYPORTAL-18840 Reformat statistic json
  AxonIvyPortal/portal/config/variables/Portal/Statistic.json
Labels: enhancement

#1917 IVYPORTAL-18007 Update performance test so that responses are as expe…
  AxonIvyPortal/portal-selenium-test/jmeter/portal_walkthrough_testplan.jmx
Labels: skip-changelog

#1918 Update pom.xml
  Documentation/maven/pom.xml
Labels: skip-changelog

#1919 IVYPORTAL-19017-Fix-Screenshots-n-GUI-tests
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
Labels: enhancement

#1920 Ivyportal 18829 implementation of pin your task case
  AxonIvyPortal/portal-selenium-test/jmeter/portal_walkthrough_testplan.jmx
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCaseWidgetActionTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetActionTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskWidgetTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
Labels: skip-changelog

#1921 Updated all pom build.plugin.version=, ivy.engine.version=, version=1…
  AxonIvyPortal/AxonIvyExpress/pom.xml
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-product/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Documentation/public-api/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-demo-app/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1922 IVYPORTAL-18714 Add statistic tests
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/ComplexFilterHelper.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/StatisticConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/StatisticWidgetTest.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/page/StatisticConfiguration/StatisticConfiguration.xhtml
Labels: skip-changelog

#1925 Feature/ivyportal 18840 portal 13.1 quality pass le
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Documentation/public-api/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1926 IVYPORTAL-19017 update document statistic
  AxonIvyPortal/portal/config/variables/Portal/Statistic.json
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-statistic-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/settings/index.rst
Labels: enhancement, skip-changelog

#1927 IVYPORTAL-19019 Update document feedback from PO
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
Labels: skip-changelog

#1928 IVYPORTAL-19019 Update document feedback from PO
  Documentation/portal-guide/source/portal-developer-guide/installation/index.rst
Labels: skip-changelog

#1930 Update DashboardConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/dashboard/converter/v131/DashboardConverter.java
Labels: skip-changelog

#1932 IVYPORTAL-18840: Portal 13.1 Quality Pass
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1937 Update PortalSecurity.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/security/PortalSecurity.java
Labels: skip-changelog

#1939 IVYPORTAL-18840 Portal 13.1 Quality Pass
  AxonIvyPortal/portal/pom.xml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/security/PortalSecurity.java
Labels: skip-changelog

#1945 Ivyportal 18840 portal 13.1 quality pass
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskPriorityChangeTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/security/PortalSecurity.java
Labels: skip-changelog

#1935 MARP-2409 German translation for Portal on the MarketPlace website
  AxonIvyPortal/portal-product/zip.xml
Labels: bug

#1951 Update Jenkinsfile
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1947 Translations update from Hosted Weblate
  AxonIvyPortal/portal/cms/cms_de.yaml
Labels: skip-changelog

#1954 Translations update from Hosted Weblate
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
Labels: skip-changelog

#1958 IVYPORTAL-18840 Portal 13.1 Quality Pass
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/chat/ChatGroupUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/chat/ChatMessageManager.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/chat/ChatReferencesContainer.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/chat/ChatService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/chat/ClusterChatEventListener.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/chat/ClusterChatEventSender.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/ChatAssigneeBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/RoleManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/DashboardProcessCaseLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/DashboardProcessTaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/role/RoleHolder.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/WidgetDateFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldCreator.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/CaseFilterFieldState.java
Labels: skip-changelog

#1955 IVYPORTAL-18980 Portal update pom not update engine in maven cache if…
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1962 feature/IVYPORTAL-18260-Create-Github-workflow-for-selenium-test-12-Test
  .github/workflows/portal-selenium-test.yml
Labels: enhancement, skip-changelog

#1965 Ivyportal 18840 portal 13.1 quality pass
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
Labels: skip-changelog

#1968 Update Jenkinsfile
  build/create-release/Jenkinsfile
Labels: skip-changelog

#1969 Revert Jenkinsfile
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1970 Ivyportal 18840 portal 13.1 quality pass
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDescriptionChangeTest.java
Labels: skip-changelog

#1971 Updated all pom build.plugin.version=13.1.1, ivy.engine.version=13.2.…
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1973 Ivyportal 18840 portal 13.1 quality pass 13.1
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EscalationTaskTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDescriptionChangeTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskDetailsTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskPriorityChangeTest.java
Labels: skip-changelog

#1974 Update Jenkinsfile
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1980 Update pom.xml
  AxonIvyPortal/portal-components/pom.xml
Labels: skip-changelog

#1981 Update portal kit test helper
  AxonIvyPortal/PortalKitTestHelper/pom.xml
Labels: skip-changelog

#1982 Update pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
Labels: skip-changelog

#1983 Update pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
Labels: skip-changelog

#1988 Update build
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/portal-product/pom.xml
  Showcase/portal-demo-app/pom.xml
  build/create-release/Jenkinsfile
Labels: skip-changelog

#1991 Adapt project conversion
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-product/pom.xml
  Showcase/portal-demo-app/pom.xml
  build/create-release/Jenkinsfile
Labels: skip-changelog

#2000 Update portal-documentation.yml
  .github/workflows/portal-documentation.yml
Labels: skip-changelog

#2003 feature/IVYPORTAL-18260-Create-Github-workflow-for-selenium-test
  .github/workflows/portal-selenium-test.yml
Labels: enhancement, skip-changelog

#2004 Update cron-bot.yml
  .github/workflows/cron-bot.yml
Labels: enhancement, skip-changelog
