Repository axonivy-market/portal, pull requests merged in 2025-03, with the labels that each got.

#1590 Update cron-bot.yml
  .github/workflows/cron-bot.yml
Labels: skip-changelog

#1591 fix-test-for-release-10.0.26
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/GlobalGrowlTest.java
Labels: enhancement

#1594 feature/IVYPORTAL-18399-Enhancement-Case-Owners-Can-Delegate-Tasks
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/security/PortalSecurity.java
Labels: enhancement

#1593 Feature/ivyportal 18538 check all portal for java script injection prevention 12
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/HtmlSanitizerBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/HtmlUtils.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/IFrameTaskConfig/IFrameTaskConfig.xhtml
Labels: enhancement

#1572 Feature/ivyportal 18538 check all portal for java script injection prevention
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/HtmlSanitizerBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/HtmlUtils.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/IFrameTaskConfig/IFrameTaskConfig.xhtml
Labels: enhancement

#1599 IVYPORTAL 18602 release 10.0.26 update pom.xml
  Documentation/maven/pom.xml
Labels: enhancement

#1596 IVYPORTAL-18305 Deploy Portal to dev engines without creating new PMV - v10
  build/ci/Jenkinsfile
  build/performance-test/Jenkinsfile
Labels: skip-changelog

#1601 IVYPORTAL-18602-update-pom.xml-to-10.0.27-SNAPSHOT
  Documentation/maven/pom.xml
Labels: enhancement

#1597 IVYPORTAL-18305 Deploy Portal to dev engines without creating new PMV - v12
  build/ci/Jenkinsfile
  build/performance-test/Jenkinsfile
Labels: skip-changelog

#1598 IVYPORTAL-18305 Deploy Portal to dev engines without creating new PMV - v13
  build/ci/Jenkinsfile
  build/performance-test/Jenkinsfile
Labels: skip-changelog

#1604 IVYPORTAL-18611: Update cron for selenium and screenshot tests
  build/document-screenshot-selenide/Jenkinsfile
  build/gui-test-new-dashboard/Jenkinsfile
Labels: enhancement

#1606 IVYPORTAL-18611: Update cron for selenium and screenshot tests
  build/document-screenshot-selenide/Jenkinsfile
  build/gui-test-new-dashboard/Jenkinsfile
Labels: enhancement

#1612 release-Portal-12.0.4-update-revision
  Documentation/maven/pom.xml
Labels: enhancement, skip-changelog

#1613 IVYPORTAL-18603-update-revision-to-12.0.5-SNAPSHOT
  Documentation/maven/pom.xml
Labels: enhancement

#1616 IVYPORTAL-18559: Adapt documentation for sanitizing java script code
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/HtmlSanitizerBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/publicapi/SanitizeAPI.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/HtmlUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/error/ErrorPage/ErrorPage.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/PasswordResetErrorPage/PasswordResetErrorPage.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/GlobalAjaxStatus/GlobalAjaxStatus.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/IconSelection/IconSelection.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/RoleManagement/RoleManagement.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/feature/WarnOnClosingBrowserTab/WarnOnClosingBrowserTab.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/multiapp/settings/LogoutSetting/LogoutSetting.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/singleapp/general/PasswordReset/PasswordReset.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/ShareLinkDialog/ShareLinkDialog.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml
  AxonIvyPortal/portal/webContent/resources/js/icon-selection.js
  AxonIvyPortal/portal/webContent/resources/js/process-widget.js
  Showcase/InternalSupport/src_hd/internaltest/ui/SaleDepartment/SaleDepartment.xhtml
  Showcase/InternalSupport/webContent/layouts/frame-10-full-width.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/customization/iframe/Frame10FullWidthCard/Frame10FullWidthCard.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/customization/iframe/Frame10FullWidthNoCard/Frame10FullWidthNoCard.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/customization/iframe/Frame10WithCard/Frame10WithCard.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/Approve/Approve.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/CreateInvestment/CreateInvestment.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/CustomParamsForIFrame/CustomParamsForIFrame.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/CustomTaskNameForIFrame/CustomTaskNameForIFrame.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/Review/Review.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/TemplateExampleInFrame/TemplateExampleInFrame.xhtml
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/ExampleHomePage/ExampleHomePage.xhtml
Labels: enhancement

#1615 IVYPORTAL-18559: Adapt documentation for sanitizing java script code
  Documentation/portal-guide/source/portal-developer-guide/iframe/index.rst
Labels: documentation, skip-changelog

#1626 IVYPORTAL-18632-Release-13.1.0-m272-UPDATE-POM
  Documentation/maven/pom.xml
Labels: enhancement

#1592 IVYPORTAL-18399 Case owner can delegate related tasks of case
  AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/GrantPermissions.p.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/caze/CaseDetailsTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/PortalPermission.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/CaseUtils.java
  Documentation/portal-guide/source/portal-developer-guide/permissions/index.rst
  Documentation/portal-guide/source/portal-developer-guide/settings/index.rst
Labels: feature

#1607 feature/IVYPORTAL-18388-Integrate-Japanese-Translations-in-portal-LE
  AxonIvyPortal/portal-components/cms/cms_ja.yaml
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables/Portal/ClientStatistic.json
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/CloneWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardCustomWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/navigation/PortalNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetConfigurationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/casefilter/impl/CaseOwnerFilter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/Dashboard.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/PasswordCheckingService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/SecurityMemberDisplayNameUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/UserUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/CaseWidgetConfigurationFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/TaskWidgetConfigurationFilterBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CustomDashboardWidget/CustomDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/SelectDeputy.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskListHeader/TaskListHeader.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/multiapp/settings/PasswordSetting/PasswordSetting.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/portalException.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/css/module.css
  Showcase/portal-components-examples/cms/cms_ja.yaml
  Showcase/portal-developer-examples/cms/cms_ja.yaml
  Showcase/portal-user-examples/cms/cms_ja.yaml
  Showcase/portal-user-examples/src/com/axonivy/portal/userexamples/utils/Dates.java
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/InvestmentList/InvestmentListProcess.p.json
Labels: enhancement

#1595 Feature/ivyportal 18388 integrate japanese translations in portal
  AxonIvyPortal/portal-components/cms/cms_ja.yaml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables/Portal/ClientStatistic.json
  AxonIvyPortal/portal/config/variables/Portal/Dashboard.json
  AxonIvyPortal/portal/config/variables/Portal/DashboardTemplates.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardCustomWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/navigation/PortalNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetConfigurationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/casefilter/impl/CaseOwnerFilter.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/Dashboard.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/PasswordCheckingService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DefaultDashboardUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/SecurityMemberDisplayNameUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/UserUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/CaseWidgetConfigurationFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/TaskWidgetConfigurationFilterBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CustomDashboardWidget/CustomDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/SelectDeputy.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskListHeader/TaskListHeader.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/multiapp/settings/PasswordSetting/PasswordSetting.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/DashboardImportDetails/DashboardImportDetails.xhtml
  AxonIvyPortal/portal/webContent/layouts/BasicTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/portalException.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/css/module.css
  Showcase/portal-components-examples/cms/cms_ja.yaml
  Showcase/portal-developer-examples/cms/cms_ja.yaml
  Showcase/portal-user-examples/cms/cms_ja.yaml
  Showcase/portal-user-examples/src/com/axonivy/portal/userexamples/utils/Dates.java
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/InvestmentList/InvestmentListProcess.p.json
Labels: enhancement

#1634 Updated all pom build.plugin.version=, ivy.engine.version=10.0.27, ve…
  AxonIvyPortal/AxonIvyExpress/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1610 IVYPORTAL-18363 Remove trigger by change
  build/gui-test-new-dashboard/Jenkinsfile
Labels: enhancement, skip-changelog

#1611 IVYPORTAL-18363 Remove trigger by change
  build/gui-test-new-dashboard/Jenkinsfile
Labels: enhancement, skip-changelog

#1537 IVYPORTAL-17382 Multi Language support for Custom field
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-case-widget-has-quicksearch.json
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-task-widget-has-quicksearch.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/QuickSearchTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/AbstractColumn.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/ColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CaseColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardCaseSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/WidgetFilterService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/PortalCustomFieldUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/WidgetTextFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/custom/CaseFilterFieldCustomString.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/custom/TaskFilterFieldCustomString.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/caze/customfield/CustomStringContainsOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/caze/customfield/CustomStringInOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/customfield/CustomStringContainsOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/customfield/CustomStringInOperatorHandler.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/TextFilter/TextFilter.xhtml
  Showcase/portal-developer-examples/cms/cms_de.yaml
  Showcase/portal-developer-examples/cms/cms_en.yaml
  Showcase/portal-developer-examples/cms/cms_es.yaml
  Showcase/portal-developer-examples/cms/cms_fr.yaml
  Showcase/portal-developer-examples/config/custom-fields.yaml
  Showcase/portal-developer-examples/processes/Start Processes/CreateTestData.p.json
Labels: enhancement

#1623 IVYPORTAL-18559: Adapt documentation for sanitizing java script code
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/publicapi/SanitizeAPI.java
  Documentation/portal-guide/source/portal-developer-guide/components/layout-templates.rst
Labels: enhancement

#1618 Document/IVYPORTAL-17382 Multi-Language Support for Custom Fields
  Documentation/portal-guide/source/portal-developer-guide/dashboard/images/new-dashboard-case-widget/cms-structure-case-field.png
  Documentation/portal-guide/source/portal-developer-guide/dashboard/images/new-dashboard-task-widget/cms-structure-task-field.png
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
Labels: documentation

#1635 Updated all pom build.plugin.version=, ivy.engine.version=12.0.5, version
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1639 bug/Update-document-LE
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
Labels: skip-changelog

#1640 bug/Fix-fail-tests-12
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ChangePasswordPage.java
Labels: skip-changelog

#1624 IVYPORTAL-17441 Create custom charts for portal statistics
  Documentation/portal-guide/source/portal-developer-guide/settings/index.rst
Labels: documentation

#1632 IVYPORTAL-18551 Improve behavior for issues with portal picture upload
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/processes/Functional Processes/UploadDocument.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetConfigurationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ExternalLinkBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/DocumentDetectorFactory.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/DocumentExtensionConstants.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/ExcelDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/PDFDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/SVGSecurityScanner.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/WordDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/masterdata/MasterData.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/ExternalLinkUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/PortalSanitizeUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/UploadDocumentUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/WelcomeWidgetUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1641 IVYPORTAL-18551 Improve behavior for issues with portal picture upload 12
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/processes/Functional Processes/UploadDocument.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetConfigurationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ExternalLinkBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/DocumentDetectorFactory.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/DocumentExtensionConstants.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/ExcelDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/PDFDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/SVGSecurityScanner.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/WordDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/masterdata/MasterData.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/ExternalLinkUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/PortalSanitizeUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/UploadDocumentUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/WelcomeWidgetUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1642 Feature/IVYPORTAL-18551 Improve behavior for issues with portal picture upload 10
  AxonIvyPortal/AxonIvyExpress/processes/Functional Processes/CustomUploadDocumentItem.p.json
  AxonIvyPortal/AxonIvyExpress/src/ch/ivy/gawfs/beans/EmailBean.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/processes/Functional Processes/UploadDocument.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetConfigurationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ExternalLinkBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ProcessWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/DocumentDetectorFactory.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/DocumentExtensionConstants.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/ExcelDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/PDFDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/SVGSecurityScanner.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/document/WordDocumentDetector.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/masterdata/MasterData.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/ExternalLinkUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/PortalSanitizeUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/UploadDocumentUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/WelcomeWidgetUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1636 IVYPORTAL-18535 Dashboard cache issue in edit mode
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
Labels: enhancement, skip-changelog

#1649 feature/Update-revision-in-documetation-POM
  Documentation/maven/pom.xml
Labels: enhancement, skip-changelog

#1650 feature/Update-revision-in-documetation-POM
  Documentation/maven/pom.xml
Labels: enhancement

#1651 feature/Revert-revision-in-documetation-POM
  Documentation/maven/pom.xml
Labels: enhancement

#1619 IVYPORTAL-18600 Update Translation in German
  AxonIvyPortal/portal/cms/cms_de.yaml
  Showcase/portal-developer-examples/cms/cms_de.yaml
Labels: enhancement

#1674 Feature/ivyportal 18691 use version range in dependencies of pom files to build portal on demo/performance engine v13
  build/Dockerfile.python
  build/ci/Jenkinsfile
  build/common/utils.groovy
  build/performance-test/Jenkinsfile
  build/update-pom/Jenkinsfile
Labels: enhancement

#1675 IVYPORTAL-18691 Use version range in dependencies of pom files to deploy Portal to engines
  build/Dockerfile.python
  build/ci/Jenkinsfile
  build/common/utils.groovy
  build/performance-test/Jenkinsfile
  build/update-pom/Jenkinsfile
Labels: enhancement, skip-changelog

#1677 IVYPORTAL-18436 Use version range in dependencies of pom files to deploy Portal to engines
  build/Dockerfile.python
  build/ci/Jenkinsfile
  build/common/utils.groovy
  build/performance-test/Jenkinsfile
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1644 IVYPORTAL-18450-Process-list-in-compact-mode-background-color-of-item-is-not-nice
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
Labels: enhancement, skip-changelog

#1676 IVYPORTAL-18633-Error-When-Saving-Absence
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/AbsenceManagementProcess.p.json
Labels: bug, enhancement

#1648 IVYPORTAL-17305 List active absences in the absence management of the portal
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/AbsenceManagementBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/UserUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/AbsenceManagement.xhtml
Labels: enhancement

#1652 IVYPORTAL-18238 Related tasks of case table column not align
  AxonIvyPortal/portal/webContent/resources/css/portal.css
Labels: skip-changelog

#1653 IVYPORTAL-18238 Related tasks of case table column not align 12
  AxonIvyPortal/portal/webContent/resources/css/portal.css
Labels: skip-changelog

#1654 IVYPORTAL-18308 Update version support in readme.md
  README.md
Labels: skip-changelog

#1566 feature/IVYPORTAL 18454 Not found message in Portal does not change by user language
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
Labels: enhancement

#1685 Feature/ivyportal 18454 Not found message in portal not change by language
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardDetails/DashboardDetails.xhtml
Labels: enhancement

#1622 IVYPORTAL-18554 Drop support for Serenity theme since 13.1
  Documentation/portal-guide/source/portal-components/index.rst
Labels: skip-changelog

#1673 IVYPORTAL-17382 Multi-Language Support for Custom Fields (#1618)
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-case-widget-has-quicksearch.json
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-task-widget-has-quicksearch.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ChangePasswordPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/QuickSearchTest.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/AbstractColumn.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/ColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/casecolumn/CaseColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/taskcolumn/TaskColumnModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardCaseSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/WidgetFilterService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/PortalCustomFieldUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/WidgetTextFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/caze/custom/CaseFilterFieldCustomString.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/task/custom/TaskFilterFieldCustomString.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/caze/customfield/CustomStringContainsOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/caze/customfield/CustomStringInOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/customfield/CustomStringContainsOperatorHandler.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/operator/task/customfield/CustomStringInOperatorHandler.java
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/filter/TextFilter/TextFilter.xhtml
  Documentation/portal-guide/source/portal-developer-guide/dashboard/images/new-dashboard-case-widget/cms-structure-case-field.png
  Documentation/portal-guide/source/portal-developer-guide/dashboard/images/new-dashboard-task-widget/cms-structure-task-field.png
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-case-widget.rst
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-task-widget.rst
  Showcase/portal-developer-examples/cms/cms_de.yaml
  Showcase/portal-developer-examples/cms/cms_en.yaml
  Showcase/portal-developer-examples/cms/cms_es.yaml
  Showcase/portal-developer-examples/cms/cms_fr.yaml
  Showcase/portal-developer-examples/config/custom-fields.yaml
  Showcase/portal-developer-examples/processes/Start Processes/CreateTestData.p.json
Labels: enhancement, feature

#1683 IVYPORTAL-18611 Update cron for Portal builds
  .github/workflows/cron-bot.yml
  .github/workflows/portal-document-screenshot-test.yml
  .github/workflows/portal-documentation.yml
  build/gui-test-new-dashboard/Jenkinsfile
  build/performance-test/Jenkinsfile
Labels: skip-changelog

#1684 IVYPORTAL-18611 Update cron for Portal builds
  build/gui-test-new-dashboard/Jenkinsfile
Labels: skip-changelog

#1688 IVYPORTAL-18554 Drop support for Serenity theme since 13.1
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessChainPage.java
Labels: skip-changelog

#1679 IVYPORTAL-18541 Improve task delegation by specifying group roles 10
  AxonIvyPortal/portal-components/cms/cms_de.yaml
  AxonIvyPortal/portal-components/cms/cms_en.yaml
  AxonIvyPortal/portal-components/cms/cms_es.yaml
  AxonIvyPortal/portal-components/cms/cms_fr.yaml
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/dto/RoleDTO.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/RoleSelection/RoleSelection.xhtml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/VisibilityBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/configuration/GlobalSetting.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DelegationAppendOption.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDelegate/TaskItemDelegate.xhtml
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1689 IVYPORTAL-18611 Update run name for Portal builds
  .github/workflows/portal-document-screenshot-test.yml
  .github/workflows/portal-documentation.yml
Labels: enhancement

#1690 IVYPORTAL-18611 Update run name for Portal builds
  .github/workflows/portal-document-screenshot-test.yml
  .github/workflows/portal-documentation.yml
Labels: skip-changelog

#1694 Feature/ivyportal 17305 list active absences in the absence management of the portal
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
Labels: enhancement

#1643 IVYPORTAL-18559: Sanitize Javascript strings and adapt documentation
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/HtmlSanitizerBean.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/publicapi/SanitizeAPI.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/util/HtmlUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/error/ErrorPage/ErrorPage.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/PasswordResetErrorPage/PasswordResetErrorPage.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/GlobalAjaxStatus/GlobalAjaxStatus.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/IconSelection/IconSelection.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/RoleManagement/RoleManagement.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/multiapp/settings/LogoutSetting/LogoutSetting.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/singleapp/general/PasswordReset/PasswordReset.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/NotificationFullPage/NotificationFullPage.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/ShareLinkDialog/ShareLinkDialog.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NewsWidget/NewsItem.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NewsWidget/NewsWidget.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NotificationWidget/NotificationWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/notification.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/IFrameTaskTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/CardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
  AxonIvyPortal/portal/webContent/resources/js/icon-selection.js
  Documentation/portal-guide/source/portal-developer-guide/iframe/index.rst
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/customization/iframe/Frame10FullWidthCard/Frame10FullWidthCard.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/customization/iframe/Frame10WithCard/Frame10WithCard.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/Approve/Approve.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/CreateInvestment/CreateInvestment.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/CustomParamsForIFrame/CustomParamsForIFrame.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/CustomTaskNameForIFrame/CustomTaskNameForIFrame.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/Review/Review.xhtml
  Showcase/portal-developer-examples/src_hd/com/axonivy/portal/developerexamples/testdata/TemplateExampleInFrame/TemplateExampleInFrame.xhtml
  Showcase/portal-user-examples/src_hd/com/axonivy/portal/userexamples/ExampleHomePage/ExampleHomePage.xhtml
Labels: enhancement

#1695 Bug/fix test master
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/PortalPermissionTest.java
Labels: skip-changelog

#1699 Revert "feature/Update-revision-documentation"
  Documentation/maven/pom.xml
Labels: enhancement

#1697 Feature/ivyportal 18438 spike dependency checks of thrid party libraries and set them up lts12
  Showcase/InternalSupport/resources/dtrack/docker-compose.yml
  build/common/utils.groovy
  build/create-release/Dockerfile
  build/create-release/Jenkinsfile
  build/sbom/Jenkinsfile
  renovate.json
Labels: enhancement, skip-changelog

#1693 IVYPORTAL-18541 Improve task delegation by specifying group roles
  AxonIvyPortal/portal-components/cms/cms_de.yaml
  AxonIvyPortal/portal-components/cms/cms_en.yaml
  AxonIvyPortal/portal-components/cms/cms_es.yaml
  AxonIvyPortal/portal-components/cms/cms_fr.yaml
  AxonIvyPortal/portal-components/cms/cms_ja.yaml
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/dto/RoleDTO.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/RoleSelection/RoleSelection.xhtml
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/config/variables.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/VisibilityBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/configuration/GlobalSetting.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/DelegationAppendOption.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GlobalVariable.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDelegate/TaskItemDelegate.xhtml
  Documentation/portal-guide/source/portal-user-guide/admin-settings/documents/available_settings.csv
Labels: enhancement

#1703 Feature/ivyportal 18541 improve task delegation by specifying group roles
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/configuration/GlobalSetting.java
Labels: enhancement

#1701 IVYPORTAL-18438 Dependency checks of thrid party libraries and set th…
  build/common/utils.groovy
  build/create-release/Dockerfile
  build/create-release/Jenkinsfile
  build/sbom/Jenkinsfile
  renovate.json
Labels: enhancement

#1700 IVYPORTAL-18438 Dependency checks of thrid party libraries and set th…
  Showcase/InternalSupport/resources/dtrack/docker-compose.yml
  build/common/utils.groovy
  build/create-release/Dockerfile
  build/create-release/Jenkinsfile
  build/sbom/Jenkinsfile
  renovate.json
Labels: enhancement

#1708 IVYPORTAL-18438 Delete dtrack docker compose file
  Showcase/InternalSupport/resources/dtrack/docker-compose.yml
Labels: skip-changelog
