Repository axonivy-market/portal, pull requests merged in 2025-06, with the labels that each got.

#2006 No need to trigger document at midnight
  Documentation/Jenkinsfile
Labels: skip-changelog

#2024 Feature/ivyportal 18840 update release drafter
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#2026 Ivyportal 18840 portal 13.1 quality pass
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
Labels: skip-changelog

#2027 Update image
  AxonIvyPortal/portal-product/images/axon-ivy-portal-header.png
  AxonIvyPortal/portal-product/images/portal.png
  AxonIvyPortal/portal-product/images/user-example-demo.png
Labels: skip-changelog

#2028 Ivyportal 18840 portal 13.1 quality pass
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskWidgetTest.java
Labels: skip-changelog

#2029 Ivyportal 18840 portal 13.1 quality pass 13.1
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskWidgetTest.java
  Documentation/portal-guide/source/portal-developer-guide/deployment/index.rst
  Documentation/portal-guide/source/portal-developer-guide/index.rst
Labels: skip-changelog

#2030 Chnam axonivy patch 1
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1923 IVYPORTAL-18999 Accessibility issue with Portal
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemHistory/CaseItemHistory.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemNotes/TaskItemNotes.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/CardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: enhancement

#1933 IVYPORTAL-18999 Assessibility issue with Portal
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemHistory/CaseItemHistory.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemNotes/TaskItemNotes.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/CardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: enhancement

#1931 IVYPORTAL-18999 Assessibility issue with Portal
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDetails/CaseItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDocument/CaseItemDocument.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemHistory/CaseItemHistory.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedCases/CaseItemRelatedCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDetails/TaskItemDetails.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemNotes/TaskItemNotes.xhtml
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/CardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: enhancement

#2037 Update namespace
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
Labels: skip-changelog

#2039 Update Jenkinsfile
  build/create-release/Jenkinsfile
Labels: skip-changelog

#2042 Update ivy-project-parent version
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
Labels: skip-changelog

#2043 Update namspace for release build
  build/create-release/Jenkinsfile
Labels: skip-changelog

#2044 Add namespace
  Documentation/public-api/pom.xml
Labels: skip-changelog

#2045 Revert new version from renovatebot
  Documentation/public-api/pom.xml
Labels: skip-changelog

#2051 IVYPORTAL-19041 Introduce ARIA Landmarks and Skippable Areas
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/dashboard/component/NavigationDashboardWidget/NavigationDashboardWidget.xhtml
Labels: enhancement

#2057 Updated all pom build.plugin.version=10.0.17, ivy.engine.version=10.0…
  AxonIvyPortal/AxonIvyExpress/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#2058 Updated all pom build.plugin.version=12.0.5, ivy.engine.version=12.0.…
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#2061 feature/IVYPORTAL-18946: Integrate-Portal-into-Weblate
  README.md
Labels: enhancement, skip-changelog

#2059 IVYPORTAL-18927 Improve message after closing process viewer in version 12
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessViewerPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/GlobalGrowlTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/cms/cms_ja.yaml
  AxonIvyPortal/portal/dataclasses/portalkit/GrowlMessageData.d.json
  AxonIvyPortal/portal/processes/Functional Processes/GrowlMessage.p.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/IFrameTaskTemplateBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/MasterDataBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/GrowlMessageType.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/SessionAttribute.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/GrowlMessageService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/GrowlMessageUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/NotificationBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/enums/PortalCustomSignature.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/ApplicationSelectionMenu/ApplicationSelectionMenuProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/GlobalSearch/GlobalSearchProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalFinishTaskHandle/PortalFinishTaskHandleProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/WarningBeforeLeavingTask/WarningBeforeLeavingTaskProcess.p.json
Labels: enhancement

#1992 IVYPORTAL-19041 Introduce ARIA Landmarks and Skippable Areas
  AxonIvyPortal/portal/webContent/layouts/BasicTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/CardWidget.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/decorator/TableWidget.xhtml
Labels: enhancement

#1906 IVYPORTAL-19012 Use errorPage bean to check condition to show error details
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/PortalExceptionBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/error/ErrorPage/ErrorPage.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ExceptionDialog/ExceptionDialog.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/GlobalAjaxStatus/GlobalAjaxStatus.xhtml
Labels: enhancement

#2064 IVYPORTAL-18614 Dashboard json appear styleClass attribute
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardWidgetUtils.java
Labels: enhancement, skip-changelog

#2120 IVYPORTAL-19130 Fix portal update pom > Update repositories
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Documentation/portal-guide/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-demo-app/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#2121 IVYPORTAL-19130 Fix portal update pom > Update repositories
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
Labels: skip-changelog

#2124 IVYPORTAL-19144 Missing examples for customized document processes
  Showcase/portal-components-examples/processes/Functional Processes/CustomDocumentFeatures.p.json
Labels: bug

#2109 IVYPORTAL-18513 Custom field on case widget error
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/WidgetDateFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/AbstractCaseWidgetFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bean/dashboard/filter/AbstractTaskWidgetFilterBean.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/FilterFieldFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/filter/field/TaskFilterFieldFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/validator/filter/DashboardDateFilterValidator.java
  AxonIvyPortal/portal/src/com/axonivy/portal/validator/filter/DashboardDefaultListFilterValidator.java
  AxonIvyPortal/portal/src/com/axonivy/portal/validator/filter/DashboardNumberFilterValidator.java
  AxonIvyPortal/portal/src/com/axonivy/portal/validator/filter/DashboardSelectableListFilterValidator.java
  AxonIvyPortal/portal/src/com/axonivy/portal/validator/filter/DashboardTextFilterValidator.java
Labels: enhancement

#2133 IVYPORTAL-19167 Correct translation of hour from Sunde to Stunde v12
  AxonIvyPortal/portal/cms/cms_de.yaml
Labels: skip-changelog

#2132 IVYPORTAL-19167 Correct translation of hour from Sunde to Stunde v13
  AxonIvyPortal/portal/cms/cms_de.yaml
Labels: skip-changelog

#2137 Portal update pom/master
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Documentation/portal-guide/pom.xml
  Documentation/public-api/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-demo-app/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#2138 IVYPORTAL-19144 Missing examples for customized document processes
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/enums/UploadDocumentCheckStatus.java
  AxonIvyPortal/portal/dataclasses/ch/ivy/add/portalkit/DeleteDocumentData.d.json
  AxonIvyPortal/portal/dataclasses/ch/ivy/add/portalkit/DownloadDocumentData.d.json
  AxonIvyPortal/portal/dataclasses/ch/ivy/add/portalkit/GetDocumentListData.d.json
  AxonIvyPortal/portal/processes/Functional Processes/DeleteDocument.p.json
  AxonIvyPortal/portal/processes/Functional Processes/DownloadDocument.p.json
  AxonIvyPortal/portal/processes/Functional Processes/GetDocumentList.p.json
  AxonIvyPortal/portal/processes/Functional Processes/UploadDocument.p.json
Labels: skip-changelog

#1963 IVYPORTAL-18677 Third party application with permissions
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/AdminSettingBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/ThirdPartyApplicationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/configuration/Application.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/JsonConfigurationService.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/jsonversion/AbstractJsonVersion.java
  AxonIvyPortal/portal/src/com/axonivy/portal/bo/jsonversion/ApplicationJsonVersion.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/thirdpartyapplication/converter/JsonThirdPartyApplicationConverterFactory.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/thirdpartyapplication/converter/v120/ThirdPartyApplicationConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/thirdpartyapplication/converter/v132/ThirdPartyApplicationConverter.java
  AxonIvyPortal/portal/src/com/axonivy/portal/migration/thirdpartyapplication/migrator/JsonThirdPartyApplicationMigrator.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettings.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettingsProcess.p.json
Labels: enhancement

#2143 Feature/ivyportal 18677 third party application with permissions
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettings.xhtml
Labels: enhancement

#2139 IVYPORTAL-19045 Improve Text and Background Contrast
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/css/module.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-dark.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
Labels: enhancement

#2146 IVYPORTAL-19042 Ensure Descriptive Labels on Buttons version 13
  AxonIvyPortal/portal/src_hd/com/axonivy/portal/component/NotificationFullPage/NotificationFullPage.xhtml
Labels: enhancement

#2151 Bug/ivyportal 18260 improve fail tests 12
  .github/workflows/portal-selenium-test.yml
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskIFrameTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EscalationTaskTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/UploadDeleteDocumentVisibilityTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardTaskWidgetActionTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskTemplateIFrameTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/task/TaskTemplateTest.java
Labels: skip-changelog

#2155 IVYPORTAL-19044 Correct Focus Order on Tasks/Cases Page
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/CaseDashboardWidget/CaseInfo.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/ProcessDashboardWidget/ProcessInfo.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskDashboardWidget/TaskInfo.xhtml
Labels: enhancement, feature

#2157 Feature/ivyportal 18677 third party application with permissions
  AxonIvyPortal/PortalKitTestHelper/processes/Start Processes/DataCreation.p.json
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuNavigator.java
Labels: enhancement

#2152 IVYPORTAL-19045 Improve Text and Background Contrast
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
Labels: enhancement

#2150 bug/IVYPORTAL-19191: Wrong label on statistic chart with numerical data
  AxonIvyPortal/portal/webContent/resources/js/statistic.js
Labels: bug

#2160 IVYPORTAL-19204 Create release 13.1.1
  AxonIvyPortal/PortalKitTestHelper/.settings/ch.ivyteam.ivy.designer.prefs
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/.settings/ch.ivyteam.ivy.designer.prefs
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-selenium-test/.settings/ch.ivyteam.ivy.designer.prefs
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/.settings/ch.ivyteam.ivy.designer.prefs
  AxonIvyPortal/portal/pom.xml
  Showcase/InternalSupport/.settings/ch.ivyteam.ivy.designer.prefs
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/.settings/ch.ivyteam.ivy.designer.prefs
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-developer-examples/.settings/ch.ivyteam.ivy.designer.prefs
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/.settings/ch.ivyteam.ivy.designer.prefs
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#2161 bug/IVYPORTAL-19191-Wrong-label-with-task-name-containing-number-only
  AxonIvyPortal/portal/webContent/resources/js/statistic.js
Labels: skip-changelog

#2168 Update pom.xml
  Documentation/maven/pom.xml
Labels: skip-changelog

#2148 IVYPORTAL-19191: Wrong label on statistic chart with numerical data
  AxonIvyPortal/portal/webContent/resources/js/statistic.js
Labels: bug, enhancement

#2169 Corrected screenshot download to build document
  .github/workflows/portal-documentation.yml
Labels: skip-changelog

#2165 IVYPORTAL-19207 Fix integration test by deploying portal release to local repo
  build/integration/Jenkinsfile
Labels: skip-changelog

#2171 Update TemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
Labels: enhancement

#2175 IVYPORTAL-19191 adapt when number label empty task
  AxonIvyPortal/portal/webContent/resources/js/client-statistic.js
Labels: enhancement, skip-changelog

#2176 Update pom.xml
  Documentation/maven/pom.xml
Labels: skip-changelog

#2177 Update pom.xml
  Documentation/maven/pom.xml
Labels: skip-changelog

#2178 Update portal doc version to 13.1.1
  Documentation/maven/pom.xml
Labels: skip-changelog

#2181 Updated all pom build.plugin.version=, ivy.engine.version=, version=1…
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-product/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Documentation/public-api/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-demo-app/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1957 IVYPORTAL-19036 Update deprecate method related to multiple activator on LE
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardProcessTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/DashboardTaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/TaskSearchCriteria.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/task/column/TaskListHeader/TaskListHeader.xhtml
Labels: skip-changelog

#2185 IVYPORTAL-19217 Update Github action for screenshots
  .github/workflows/portal-document-screenshot-test.yml
Labels: enhancement, skip-changelog

#2186 IVYPORTAL-19091 Fix compile error
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/loader/ResourceLoader.java
Labels: skip-changelog

#2189 Update portal-document-screenshot-test.yml
  .github/workflows/portal-document-screenshot-test.yml
Labels: skip-changelog

#2190 Update portal-document-screenshot-test.yml
  .github/workflows/portal-document-screenshot-test.yml
Labels: skip-changelog

#2191 Update portal-document-screenshot-test.yml
  .github/workflows/portal-document-screenshot-test.yml
Labels: skip-changelog

#2192 Update AdditionalComponentsScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/AdditionalComponentsScreenshotTest.java
Labels: skip-changelog

#2193 IVYPORTAL-19091 Fixed unstable test
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
Labels: skip-changelog

#2194 Revert "IVYPORTAL-19091 Fixed unstalbe test (#2193)"
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
Labels: skip-changelog

#2196 IVYPORTAL-19216 Revert documentation revision
  Documentation/maven/pom.xml
Labels: skip-changelog

#2153 IVYPORTAL-19045 Improve Text and Background Contrast
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/MenuView.java
  AxonIvyPortal/portal/webContent/resources/css/dashboard.css
  AxonIvyPortal/portal/webContent/resources/css/portal-variables-light.css
  AxonIvyPortal/portal/webContent/resources/css/portal.css
Labels: enhancement
