Repository axonivy-market/portal, pull requests merged in 2025-01, with the labels that each got.

#1366 Updated all pom build.plugin.version=, ivy.engine.version=, version=1…
  AxonIvyPortal/AxonIvyExpress/pom.xml
  AxonIvyPortal/PortalApp/pom.xml
  AxonIvyPortal/PortalKitTestHelper/pom.xml
  AxonIvyPortal/portal-components/pom.xml
  AxonIvyPortal/portal-migration/pom.xml
  AxonIvyPortal/portal-product/pom.xml
  AxonIvyPortal/portal-selenium-test/customized_pom.xml
  AxonIvyPortal/portal-selenium-test/document_screenshot_pom.xml
  AxonIvyPortal/portal-selenium-test/pom.xml
  AxonIvyPortal/portal/pom.xml
  Documentation/public-api/pom.xml
  Showcase/InternalSupport/pom.xml
  Showcase/portal-components-examples/pom.xml
  Showcase/portal-demo-app/pom.xml
  Showcase/portal-developer-examples/pom.xml
  Showcase/portal-user-examples/pom.xml
Labels: skip-changelog

#1349 Feature/ivyportal 16201 remove ajax loader
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardConfiguration/PortalDashboardConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/AbsenceManagement.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettings.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDescription/CaseItemDescription.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ColumnsConfiguration/ColumnsConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/RoleManagement/RoleManagement.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDescription/TaskItemDescription.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemNotes/TaskItemNotes.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
Labels: enhancement

#1358 Feature/ivyportal 17377 create pipeline to run lighthouse report
  .github/workflows/lighthouse-report.yml
  AxonIvyPortal/portal-selenium-test/lighthouse/package.json
  AxonIvyPortal/portal-selenium-test/lighthouse/puppeteer-script.mjs
Labels: enhancement

#1364 feature/IVYPORTAL-18237-Full-task-list-sort-not-working
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
Labels: skip-changelog

#1372 feature/IVYPORTAL-18237-Full-task-list-sort-not-working (#1364)
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/TaskWidget/TaskWidget.xhtml
Labels: enhancement

#1371 feature/IVYPORTAL-17377-Create-pipeline-to-run-Lighthouse-report
  .github/workflows/lighthouse-report.yml
Labels: enhancement

#1376 Update pom.xml for documentation release 12.0.2
  Documentation/maven/pom.xml
Labels: enhancement

#1352 IVYPORTAL-18151 Create Github Action for Building Documentation
  .github/workflows/portal-documentation.yaml
Labels: enhancement

#1377 Revert pom.xml of documentation to the next preview release 12.0.3-SN…
  Documentation/maven/pom.xml
Labels: enhancement

#1381 feature/IVYPORTAL-18215-Portal-crashes-if-changing-light-dark-mode-multiple-times-in-Absence-page
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/AbsenceManagement.xhtml
Labels: enhancement

#1383 IVYPORTAL-14419 Raise version of your portal maven artifacts to the n…
  build/update-pom/Jenkinsfile
Labels: skip-changelog

#1356 feature/IVYPORTAL-18210-SecurityError-happens-when-reloading-with-ifr…
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1332 IVYPORTAL-17710: Able use shortcut in iframe
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1379 Feature/ivyportal 17377 create pipeline to run lighthouse report 12
  .github/workflows/lighthouse-report.yml
  AxonIvyPortal/portal-selenium-test/lighthouse/package.json
  AxonIvyPortal/portal-selenium-test/lighthouse/puppeteer-script.mjs
Labels: enhancement

#1378 Feature/ivyportal 17377 create pipeline to run lighthouse report 10
  .github/workflows/lighthouse-report.yml
  AxonIvyPortal/portal-selenium-test/lighthouse/package.json
  AxonIvyPortal/portal-selenium-test/lighthouse/puppeteer-script.mjs
Labels: enhancement

#1373 feature/IVYPORTAL-16201-Remove-ajax-loader-12
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TemplatePage.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardConfiguration/PortalDashboardConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/DashboardModification/DashboardModification.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/Absence.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/AbsenceManagement.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/admin/AdminSettings/AdminSettings.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDescription/CaseItemDescription.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ColumnsConfiguration/ColumnsConfiguration.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/ProcessWidget/ProcessWidgetDialogs.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/RoleManagement/RoleManagement.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDescription/TaskItemDescription.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemDocuments/TaskItemDocuments.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskItemNotes/TaskItemNotes.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessItemAction/ProcessItemAction.xhtml
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/layouts/restricted/DashboardTemplate.xhtml
Labels: enhancement

#1385 feature/IVYPORTAL-18215-Portal-crashes-if-changing-light-dark-mode-multiple-times-in-Absence-page-12
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/AbsenceManagement.xhtml
Labels: enhancement

#1388 feature/IVYPORTAL-18210-SecurityError-happens-when-reloading-with-iframe-inside-external-page-widget-12
  AxonIvyPortal/portal/webContent/layouts/includes/topbar.xhtml
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1391 Feature/ivyportal 18117 beautify screenshots
  AxonIvyPortal/portal-selenium-test/resources/js/document-screenshot.js
  AxonIvyPortal/portal-selenium-test/resources/testFile/custom-case-details-with-url.json
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-has-one-number-chart.json
  AxonIvyPortal/portal-selenium-test/resources/testFile/dashboard-statistic-widget-demo.json
  AxonIvyPortal/portal-selenium-test/resources/testFile/task-details-custom-iframe.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardConfigurationScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DashboardScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DemoProcessesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/MultiLanguageTranslationSupportScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AdminSettingsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetNewDashBoardPage.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/process/ProcessGridItem/ProcessGridItem.xhtml
  Documentation/portal-guide/source/portal-user-guide/my-profile/index.rst
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
  Documentation/portal-guide/source/portal-user-guide/portal-multi-language/index.rst
  Documentation/portal-guide/source/portal-user-guide/statistic-chart/index.rst
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/UserSelectionExample/UserSelectionExample.xhtml
Labels: enhancement

#1393 IVYPORTAL-18151 Create Github Action for Building Documentation
  .github/workflows/cron-bot.yml
  .github/workflows/portal-documentation.yml
Labels: enhancement

#1395 IVYPORTAL 18249 disable dashboard link LE
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardDetailModification.xhtml
Labels: enhancement

#1399 IVYPORTAL-18249-Enhance-statistics-dashboard-modification-LTS12
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/PortalDashboardDetailModification/PortalDashboardDetailModification.xhtml
Labels: enhancement

#1396 IVYPORTAL-18157 Replace the deprecated method ICase.getOwner()
  AxonIvyPortal/portal/processes/Functional Processes/Navigator.p.json
  AxonIvyPortal/portal/processes/Functional Processes/OpenPortalCases.p.json
  AxonIvyPortal/portal/processes/Functional Processes/OpenPortalTasks.p.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/navigation/PortalNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/SecurityMemberDisplayNameBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/enums/PortalPage.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/SecurityMemberDisplayNameUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/PortalCaseListInFrame/PortalCaseListInFrame.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/PortalCaseListInFrame/PortalCaseListInFrameData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/PortalCaseListInFrame/PortalCaseListInFrameProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/PortalTaskListInFrame/PortalTaskListInFrame.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/PortalTaskListInFrame/PortalTaskListInFrameData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/PortalTaskListInFrame/PortalTaskListInFrameProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalCases/PortalCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalCases/PortalCasesData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalCases/PortalCasesProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalTasks/PortalTasks.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalTasks/PortalTasksData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalTasks/PortalTasksProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskListNavigator/TaskListNavigator.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskListNavigator/TaskListNavigatorData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskListNavigator/TaskListNavigatorProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasksProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseListHeader/CaseListHeader.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseOwner/CaseOwner.xhtml
  AxonIvyPortal/portal/webContent/layouts/PortalCasesTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/PortalTasksTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/TaskTemplate-8.xhtml
Labels: enhancement

#1365 IVYPORTAL-18157 Replace the deprecated method ICase.getOwner() > Repl…
  AxonIvyPortal/portal/processes/Functional Processes/Navigator.p.json
  AxonIvyPortal/portal/processes/Functional Processes/OpenPortalCases.p.json
  AxonIvyPortal/portal/processes/Start Processes/PortalStart.p.json
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/navigation/PortalNavigator.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseDetailsBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/SecurityMemberDisplayNameBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/SecurityMemberDisplayNameUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/PortalCaseListInFrame/PortalCaseListInFrame.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/PortalCaseListInFrame/PortalCaseListInFrameData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/iframe/PortalCaseListInFrame/PortalCaseListInFrameProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalCases/PortalCases.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalCases/PortalCasesData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/PortalCases/PortalCasesProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskListNavigator/TaskListNavigator.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskListNavigator/TaskListNavigatorData.d.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/TaskListNavigator/TaskListNavigatorProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemRelatedTasks/CaseItemRelatedTasksProcess.p.json
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseListHeader/CaseListHeader.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/cases/column/CaseOwner/CaseOwner.xhtml
  AxonIvyPortal/portal/webContent/layouts/PortalCasesTemplate.xhtml
  AxonIvyPortal/portal/webContent/layouts/TaskTemplate-8.xhtml
Labels: enhancement

#1414 feature/IVYPORTAL-18239-Remove-deprecated-param
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/CaseItemDescription/CaseItemDescription.xhtml
Labels: skip-changelog

#1346 IVYPORTAL-17694 Remove usages of deprecated methods Query#fromJson an…
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/datamodel/internal/CaseHistoryLazyDataModel.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/ivydata/searchcriteria/CaseSearchCriteria.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/ivydata/service/impl/CaseService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/CaseLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/TaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/internal/RelatedCaseLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/internal/RelatedTaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/CaseCategorySearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/CaseSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/TaskCategorySearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/TaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/CaseService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/TaskService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/DashboardWidgetInformationService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidgetProcess.p.json
Labels: enhancement

#1418 Feature/ivyportal 17694 remove usages of deprecated methods query from json and query as json 12
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/datamodel/internal/CaseHistoryLazyDataModel.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/ivydata/searchcriteria/CaseSearchCriteria.java
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/ivydata/service/impl/CaseService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/CaseLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/TaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/internal/RelatedCaseLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/datamodel/internal/RelatedTaskLazyDataModel.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/CaseCategorySearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/CaseSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/TaskCategorySearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/searchcriteria/TaskSearchCriteria.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/CaseService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/ivydata/service/impl/TaskService.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/service/DashboardWidgetInformationService.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portalkit/component/TaskWidget/TaskWidgetProcess.p.json
Labels: enhancement

#1369 IVYPORTAL-14337: Upgrade Example Users
  Showcase/portal-developer-examples/config/users.xml
Labels: enhancement

#1423 IVYPORTAL-14337: Upgrade Example Users (#1369)
  Showcase/portal-developer-examples/config/users.xml
Labels: enhancement

#1424 feature/IVYPORTAL-16201-Remove-ajax-loader-Handle-feedback
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/setting/AbsenceManagement/Absence.xhtml
Labels: enhancement

#1420 IVYPORTAL-18151 Create Github Action for Building Documentation
  .github/workflows/cron-bot.yml
  .github/workflows/portal-documentation.yml
Labels: enhancement

#1413 IVYPORTAL-17710: Update navigate into and out iframe
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1387 IVYPORTAL-17710: Able use shortcut in iframe (#1332)
  AxonIvyPortal/portal/webContent/resources/js/portal.js
Labels: enhancement

#1432 MARP-1053 Update release drafter workflows
  .github/workflows/publish-release-drafter.yml
Labels: enhancement

#1401 MARP-1053 Update release drafter and publisher workflows for branch release/10.0
  .github/workflows/publish-release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement

#1419 IVYPORTAL-18151 Create Github Action for Building Documentation
  .github/workflows/portal-documentation.yml
Labels: enhancement

#1435 MARP-1053 Update release drafter workflows for branch release/10.0
  .github/workflows/publish-release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement, skip-changelog

#1437 Update README.md for supported versions
  README.md
Labels: skip-changelog

#1439 Update README.md for supported versions
  README.md
Labels: skip-changelog

#1415 IVYPORTAL-18026 Long loading time for accessing case details of case …
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java
Labels: enhancement

#1440 IVYPORTAL-18316 Update the Avatar component to auto convert email to lower cases for 12
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
  AxonIvyPortal/portal-components/webContent/resources/components/avatar.xhtml
Labels: enhancement

#1441 IVYPORTAL-18316 Update the Avatar component to auto convert email to lower cases for LE
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
  AxonIvyPortal/portal-components/webContent/resources/components/avatar.xhtml
Labels: enhancement

#1425 feature/IVYPORTAL-18158-Implement-File-Preview-to-Portal-Components
  AxonIvyPortal/portal-components/cms/cms_de.yaml
  AxonIvyPortal/portal-components/cms/cms_en.yaml
  AxonIvyPortal/portal-components/cms/cms_es.yaml
  AxonIvyPortal/portal-components/cms/cms_fr.yaml
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/DocumentUploadBean.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableData.d.json
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/component/DocumentTableComponentPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/DocumentTableComponentTest.java
  Documentation/portal-guide/source/portal-components/document-table/index.rst
  Documentation/portal-guide/source/portal-components/documents/document_table_component_attributes.csv
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/CustomizedDocumentTableExample/CustomizedDocumentTableExample.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/serenity/CustomizedDocumentTableExampleSerenity/CustomizedDocumentTableExampleSerenity.xhtml
Labels: enhancement

#1409 MARP-1053 Update release drafter and publisher workflows for branch release/12.0
  .github/workflows/publish-release.yml
  .github/workflows/release-drafter.yml
Labels: enhancement

#1375 Feature/ivyportal 17306 welcome widget dark mode support 12
  .github/CODEOWNERS
  AxonIvyPortal/portal-selenium-test/resources/testFile/test-welcome-widget-image-dark-mode.png
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/WelcomeEditWidgetNewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardWelcomeWidgetTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetConfigurationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/WelcomeDashboardWidget.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/WelcomeWidgetUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
  AxonIvyPortal/portal/webContent/resources/js/welcome-widget.js
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-welcome-widget.rst
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: enhancement, skip-changelog

#1411 MARP-1053 Update release drafter and publisher workflows for branch master
  .github/workflows/publish-release.yml
Labels: enhancement

#1447 IVYPORTAL-18316 Update the Avatar component to auto convert email to lower cases LE
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
Labels: skip-changelog

#1446 IVYPORTAL-18316 Update the Avatar component to auto convert email to lower cases 12
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
Labels: skip-changelog

#1445 IVYPORTAL-18316 Update the Avatar component to auto convert email to lower cases 10
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
Labels: skip-changelog

#1421 feature/IVYPORTAL-17306-Welcome-Widget-Dark-Mode-Support-LE
  AxonIvyPortal/portal-selenium-test/resources/testFile/test-welcome-widget-image-dark-mode.png
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/BaseTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/common/WaitHelper.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/document/screenshot/DemoProcessesScreenshotTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AbsencePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/AdminSettingsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseDetailsPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseMapPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/CaseWidgetNewDashBoardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/DashboardConfigurationPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ExampleOverviewPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/LeaveRequestIFramePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/NewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/ProcessWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/RoleManagementPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/SearchResultPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskIFrameTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskTemplatePage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/TopMenuTaskWidgetPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/WelcomeEditWidgetNewDashboardPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/AbsenceTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/EnhanceVisibilityTasksForMemberOfRoleTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/NotificationsTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardCaseWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardEditCaseWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardProcessWidgetTest.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/dashboard/DashboardWelcomeWidgetTest.java
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/addon/portal/generic/menu/PortalMenuItem.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/chat/PortalSessionExtension.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/DashboardDetailModificationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CompactDashboardProcessBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/DashboardWelcomeWidgetConfigurationBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/dto/dashboard/WelcomeDashboardWidget.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/util/DashboardUtils.java
  AxonIvyPortal/portal/src/com/axonivy/portal/util/WelcomeWidgetUtils.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeDashboardWidget/WelcomeDashboardWidget.xhtml
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/generic/dashboard/component/WelcomeWidgetConfiguration/WelcomeWidgetConfiguration.xhtml
  AxonIvyPortal/portal/webContent/resources/js/welcome-widget.js
  Documentation/portal-guide/source/portal-developer-guide/dashboard/new-dashboard-welcome-widget.rst
  Documentation/portal-guide/source/portal-user-guide/new-dashboard/index.rst
Labels: enhancement

#1450 MARP-1053 Update release drafter workflows > Unified run-name
  .github/workflows/lighthouse-report.yml
  .github/workflows/portal-documentation.yml
  .github/workflows/release-drafter.yml
Labels: enhancement

#1451 MARP-1053 Update release drafter workflows > Unified run-name
  .github/workflows/lighthouse-report.yml
  .github/workflows/portal-documentation.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#1453 MARP-1053 Update release drafter workflows > Unified run-name
  .github/workflows/release-drafter.yml
Labels: enhancement

#1454 MARP-1053 Update release drafter workflows > Unified run-name
  .github/workflows/lighthouse-report.yml
  .github/workflows/portal-documentation.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#1436 IVYPORTAL-18309 Error when try to run a restricted process from the Process Overview page
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CompactProcessWidgetBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/ProcessInformation/ProcessInformation.xhtml
Labels: bug

#1438 IVYPORTAL-18309 Error when try to run a restricted process from the Process Overview page
  AxonIvyPortal/portal/cms/cms_de.yaml
  AxonIvyPortal/portal/cms/cms_en.yaml
  AxonIvyPortal/portal/cms/cms_es.yaml
  AxonIvyPortal/portal/cms/cms_fr.yaml
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CompactProcessWidgetBean.java
  AxonIvyPortal/portal/src_hd/ch/ivy/addon/portal/component/ProcessInformation/ProcessInformation.xhtml
Labels: bug

#1455 IVYPORTAL-18026 Long loading time for accessing case details of case has thousands of tasks
  AxonIvyPortal/portal/src/ch/ivy/addon/portal/generic/bean/UserMenuBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/CaseActionBean.java
  AxonIvyPortal/portal/src/ch/ivy/addon/portalkit/bean/TaskActionBean.java
Labels: enhancement

#1456 IVYPORTAL-18316: Update the Avatar component to auto convert email to lower cases
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
Labels: skip-changelog

#1458 IVYPORTAL-18316: Update the Avatar component to auto convert email to lower cases
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
Labels: skip-changelog

#1457 IVYPORTAL-18316: Update the Avatar component to auto convert email to lower cases
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/PortalComponentAvatarBean.java
Labels: skip-changelog

#1459 feature/IVYPORTAL-18158-Implement-File-Preview-to-Portal-Components
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  Documentation/portal-guide/source/portal-components/document-table/index.rst
Labels: enhancement

#1448 Feature/ivyportal 18158 implement file preview to portal components 10
  AxonIvyPortal/portal-components/cms/cms_de.yaml
  AxonIvyPortal/portal-components/cms/cms_en.yaml
  AxonIvyPortal/portal-components/cms/cms_es.yaml
  AxonIvyPortal/portal-components/cms/cms_fr.yaml
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/DocumentUploadBean.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableData.ivyClass
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/component/DocumentTableComponentPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/DocumentTableComponentTest.java
  Documentation/portal-guide/source/portal-components/document-table/index.rst
  Documentation/portal-guide/source/portal-components/documents/document_table_component_attributes.csv
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/CustomizedDocumentTableExample/CustomizedDocumentTableExample.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/DocumentTableExample/DocumentTableExample.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/serenity/CustomizedDocumentTableExampleSerenity/CustomizedDocumentTableExampleSerenity.xhtml
Labels: enhancement

#1443 feature/IVYPORTAL-18158 Implement File Preview to Portal Components 12
  AxonIvyPortal/portal-components/cms/cms_de.yaml
  AxonIvyPortal/portal-components/cms/cms_en.yaml
  AxonIvyPortal/portal-components/cms/cms_es.yaml
  AxonIvyPortal/portal-components/cms/cms_fr.yaml
  AxonIvyPortal/portal-components/src/com/axonivy/portal/components/bean/DocumentUploadBean.java
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTable.xhtml
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableData.d.json
  AxonIvyPortal/portal-components/src_hd/com/axonivy/portal/components/DocumentTable/DocumentTableProcess.p.json
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/page/component/DocumentTableComponentPage.java
  AxonIvyPortal/portal-selenium-test/src_test/com/axonivy/portal/selenium/test/DocumentTableComponentTest.java
  Documentation/portal-guide/source/portal-components/document-table/index.rst
  Documentation/portal-guide/source/portal-components/documents/document_table_component_attributes.csv
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/CustomizedDocumentTableExample/CustomizedDocumentTableExample.xhtml
  Showcase/portal-components-examples/src_hd/com/axonivy/portal/components/examples/serenity/CustomizedDocumentTableExampleSerenity/CustomizedDocumentTableExampleSerenity.xhtml
Labels: enhancement

#1462 IVYPORTAL-18357: Revert Update documentation pom to 10.0.25
  Documentation/maven/pom.xml
Labels: enhancement

#1465 IVYPORTAL-18325: Update document pom release 12.0.3
  Documentation/maven/pom.xml
Labels: enhancement

#1466 IVYPORTAL-18325: Revert Update document pom release 12.0.3
  Documentation/maven/pom.xml
Labels: enhancement

#1471 IVYPORTAL-18325 Update documentation pom to 13.1.0-m270
  Documentation/maven/pom.xml
Labels: enhancement

#1473 Revert "IVYPORTAL-18325 Update documentation pom to 13.1.0-m270 (#1471)"
  Documentation/maven/pom.xml
Labels: enhancement
